### ISSUE TITLE
Circular references in ObjC

### ISSUE THREAD

**Issue by ErikGoldman** [dropbox/djinni#10]
Hey guys, I think #4 is resurfacing.

If I have
```
ClientListener = interface +j +o {
    onClientInitialized(client: Client);
}

Client = interface +c {
    static createClient(baseUrl: string, listener: ClientListener);
}
```

Then I get an ObjectiveC ClientListener.h file referencing Client.h and a Client.h file referencing ClientListener.h.

This was tested on ed6ef3c51923fb072cbb5b9fc7acacf4659d78d7

Thanks!

**Comment by j4cbo** [comment]
Fixed now.
