### ISSUE TITLE
Generate ObjC generics

### ISSUE THREAD

**Issue by j4cbo** [dropbox/djinni#103]
Starting in Xcode 7, ObjC supports generics, e.g. `NSArray<NSString *> *foo`, and these translate nicely to Swift. They're not particularly strongly typed but better than nothing. We should optionally emit these.

(Source: https://developer.apple.com/swift/blog/?id=29 and WWDC presentations. Need to find more detailed docs.)

**Comment by mknejp** [comment]
> Aside from than these Foundation collection classes, Objective-C lightweight generics are ignored by Swift. Any other types using lightweight generics are imported into Swift as if they were unparameterized.

https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH3-ID60

**Comment by j4cbo** [comment]
Yeah, that's fine - "generate" may be the wrong word here. We don't emit our own parametric types, but we do spit out lots of references to `NSArray` / `NSDictionary` et al, and we should specify the contained type there.

Example:
https://github.com/dropbox/djinni/blob/master/test-suite/generated-src/objc/DBNestedCollection.h (unadorned `NSArray *`, vs. `std::vector<std::unordered_set<std::string>>` and `ArrayList<HashSet<String>>`)

**Comment by mknejp** [comment]
It should be a trivial change assuming they don't blow it up during Beta.
