### ISSUE TITLE
JNI generator produces broken code for methods with parameters named "data"

### ISSUE THREAD

**Issue by mrdomino** [dropbox/djinni#105]
The method parameter names for the JNI methods appear to be taken from the interface. The JNI helper declares a local variable named "data" (see `src/source/JNIGenerator.scala:131`). If any method parameter is also named "data", it is shadowed, generally producing a compile error.

One solution to this would be to automatically generate parameter names for JNI helpers. Another would be to prefix all local variables in helper methods with something like "djinni_", and to refuse to accept interfaces that use that prefix in a parameter name.

**Comment by mknejp** [comment]
Can you give an example `.djinni` that creates this broken code?

Are you sure it is `src/source/JNIGenerator.scala:131` with this problem? The function generated around this line only has two hardcoded parameters: `jniEnv` and `c`.

In all functions with user-declared JNI parameters they each get a `j_` prefix.

**Comment by mrdomino** [comment]
https://gist.github.com/mrdomino/c288bfe2a617dafb6890

Compare foo.cpp:17 and foo.cpp:20. This is against upstream master as of today.

**Comment by mrdomino** [comment]
Thanks!
