### ISSUE TITLE
Java CPP exception parameter doesn't do anything

### ISSUE THREAD

**Issue by izacus** [dropbox/djinni#108]
When using the Java CPP exception parameter (`--java-cpp-exception`), Djinni will add a `throws` declaration to every Java proxy class of that type. However when a C++ exception is actually thrown, a `java.lang.RuntimeException` is thrown everytime.

This come from the fact, that the `RuntimeException` class is hardcoded in `djinni_support.cpp` library in https://github.com/dropbox/djinni/blob/master/support-lib/jni/djinni_support.cpp#L461 and does not take set exception class name into account.

**Comment by artwyman** [comment]
This is as-designed.  If you use --java-cpp-exception, you need to provide your own exception translation by replacing some of the weakly-defined functions in the Djinni support library.  There's now an example of how to do it here: https://github.com/dropbox/djinni/blob/master/extension-libs/jni-exceptions/custom_exception_type.cpp
It's also explained in our second CppCon talk here: bit.ly/djinnivideo2
