### ISSUE TITLE
windows build issue, unable to load main class

### ISSUE THREAD

**Issue by samuelagm** [dropbox/djinni#111]
I have been trying to build djinni on windows but i get stuck on this error:
/start.bat: line 1: @echo: command not found
Error: Could not find or load main class %JOPTS%
make: *** [GypAndroid.mk] Error 1

**Comment by vmaks** [comment]
Hi,
Try to use MinGW or Git on windows instead of cygwin.
I have fixed an issue with windows build:
https://github.com/dropbox/djinni/pull/200
