### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by tpecholt** [dropbox/djinni#116]
I had quite a hard time to make djinni generator work on windows. I can remember these issues:
- big problem is everything is done in .sh scripts. So I had no other option than go for cygwin. I think nowadays CMake would be far superior solution
- these scripts call some bat files but "bat" extension is missing so they don't work
- in src/support/sbt java is called. I found out that under windows it however doesn't accepts forward / in paths (which even cmd.exe understands at least to some extent). So I had to use cygpath -pw calls to convert the paths to windows native format.
- when generator was finally built for some reason it never prefixes JNI generated files so they get same names as generated c++ interface headers. This leads to errors coming from unrecognized #includes. I tried several options on djinni command line but I never got it to work so I ended up using --jni-include-prefix Native which works and renaming all jni files by script. Interesting thing is your github readme says in a table these jni files should get a prefix.
- source code uses **attribute(noreturn)** at some places. This is gcc syntax so it doesn't compile on windows. I think I even spotted some #ifdefs for MSVC but it's not used everywhere

Well the CMake integration would definitely take some time because your building scripts are not trivial but it would help a lot. That should then fix the other 2 problems as well. 

But as for the last 2 options I think they are easy to fix.

Thanks for your work,
Tomas

**Comment by tpecholt** [comment]
OK so I found new option --ident-jni-file. It seems this one does the trick with file renames. 1 problem solved:)

**Comment by zkkzkk32312** [comment]
I am having the same issue here, sort of.

I am using :
Android Studio 1.3
Gradle Version 2.4 (Automatically used by Android Studio)
Android Plugin Version 1.2.3 (Automatically used by Android Studio)
Android NDK r10e

Changes I made to try to get rid of errors.
-runProguard false => minifyEnabled false
-File ndkDir = project.getPlugins().getPlugin('android').ndkFolder => File ndkDir = project.getPlugins().getPlugin('android').sdkHandler.getNdkFolder()
-def ndkBuildExecutable = new File(ndkDir, 'ndk-build') => def ndkBuildExecutable = new File(ndkDir, 'ndk-build.cmd')

I was not able to build through Android Studio or Cygwin.

From the IDE, i get errors:

:app:ndkBuild
process_begin: CreateProcess(NULL, git clone https://chromium.googlesource.com/external/gyp.git ./deps/gyp, ...) failed.
make (e=2): The system cannot find the file specified.
jni/Android.mk:3: ../../../GypAndroid.mk: No such file or directory

...(repeat)

Error:(87) Android NDK: WARNING: No modules to build  your APP_MODULES definition is probably incorrect!   
make.exe: *** No rule to make target `../../../GypAndroid.mk'.  Stop.
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'D:\adt-bundle-windows-x86-20130917\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2



From Cygwin:

Building Djinni...
Error: Unable to access jarfile /cygdrive/d/workspace/djinni-master/src/support/                                      sbt-launch.jar
Makefile:23: recipe for target 'GypAndroid.mk' failed
make[1]: *** [GypAndroid.mk] Error 1
make[1]: Leaving directory '/cygdrive/d/workspace/djinni-master'
Makefile:4: recipe for target 'android' failed
make: *** [android] Error 2

**Comment by vmaks** [comment]
Try to use MinGW or Git on windows instead of cygwin.
I have fixed an issue with windows build:
https://github.com/dropbox/djinni/pull/200
