### ISSUE TITLE
@import directive fails if the file supplied via --idl has no path.

### ISSUE THREAD

**Issue by chorakm** [dropbox/djinni#118]
all.djinni:
`@import "other.djinni"`

Running ./djinni/src/run --idl all.djinni throws an exception: `Error reading from --idl file: null/other.djinni (No such file or directory)`

The parser fails because it is trying to resolve the parent directory of `"all.djinni"` which ends up being (null). It tries to open `null/other.djinni` which fails.
If we put the idl file in a sub directory, running ./djinni/src/run --idl idl/all.djinni, the parser resolves the parent directory of all.djinni to be idl, and imports the file correctly: `idl/other.djinni`

**Comment by guycnicholas** [comment]
This issue was fixed with PR 190, https://github.com/dropbox/djinni/commit/f2e355725a30831e305738d0f568138f0e997644
