### ISSUE TITLE
Should CppProxy in java interfaces be public?

### ISSUE THREAD

**Issue by mrdomino** [dropbox/djinni#121]
It seems that clients should never have to call this directly. Is there any reason it's a public member?

**Comment by mknejp** [comment]
I don't think so. JNI doesn't care about access restrictions and the whole child class has always been a thorn in my eye.

**Comment by mrdomino** [comment]
Edited so the question in the title and the question in the body are the same question. (I assume from context that you were responding to the question in the body, not the title.)
