### ISSUE TITLE
Same file processed multiple times

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#125]
I recently saw someone manage to setup their `.djinni` files and `@imports` in such a way that the same file was imported multiple times and threw errors about redefined types. Unfortunately the file setup is no longer available to me but it seemed to be caused by a series of `..` entries in the `@import`s as files were referencing each other. The resulting error message contained many entries in the form of `../dir/../` etc.

I haven't found a reproducible setup yet but I assume it happens in the parser as the `File` instances do not store canonical paths to files for the duplication check. If anyone runs into such an error with their setup it'd be good to see it so I can check this assumption.

**Comment by artwyman** [comment]
Fixed in #273
