### ISSUE TITLE
ImportError: No module named android

### ISSUE THREAD

**Issue by K-Constantine** [dropbox/djinni#128]
I get this error running the make 

./example/run_djinni.sh
Already up to date: Djinni
Parsing...
Resolving...
Generating...
Copying generated code to final directories...
djinni completed.
ANDROID_BUILD_TOP=dirname  deps/gyp/gyp --depth=. -f android -DOS=android -Icommon.gypi example/libtextsort.gyp --root-target=libtextsort_jni
Traceback (most recent call last):
  File "deps/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/python2.7/dist-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/python2.7/dist-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "/usr/local/lib/python2.7/dist-packages/gyp-0.1-py2.7.egg/gyp/__init__.py", line 91, in Load
    generator = __import__(generator_name, globals(), locals(), generator_name)
ImportError: No module named android
make: *** [GypAndroid.mk] Error 1

**Comment by tripplemac** [comment]
This is because the gyp project does not contain the generator for android anymore. It has been removed recently. 

A quick workaround for me was to copy the `android.py` from the older version of gyp and instruct the gyp to use that old generator. You can do this by specifying the -f option for the gyp. For example, if the the android generator is copied to `gyp_extensions/android.py`, then you would need to change your `Makefile` like this:
```
ANDROID_BUILD_TOP=$(shell dirname `which ndk-build`) deps/gyp/gyp --depth=. -f  "gyp_extensions/android.py" -DOS=android -Icommon.gypi example/libtextsort.gyp --root-target=libtextsort_jni
```

**Comment by K-Constantine** [comment]
Damn!!! it worked!!! are you human? :d but i think i have an odd version of android.py. i get  'module' object has no attribute 'generator_default_variables'

**Comment by tripplemac** [comment]
This is the `android.py` file I have: https://www.dropbox.com/s/2fgfez0uu22am06/android.py?dl=0

**Comment by K-Constantine** [comment]
Lord! you are awesome.... done and works great but please do you have any idea on why static keyword in djinni should throw any error

[arm64-v8a] SharedLibrary  : libapplication_jni.so
/payporte/android/application/android/app//obj/local/arm64-v8a/objs/application_jni/application/generated-src/jni/NativeOak.o: In function `Java_com_romflex_payporte_Oak_getInstance':
/payporte/android/application/android/app/../../../application/generated-src/jni/NativeOak.cpp:69: undefined reference to `oaktree::Oak::get_instance(std::string const&)'
collect2: error: ld returned 1 exit status
make[1]: *** [/payporte/android/application/android/app//obj/local/arm64-v8a/libapplication_jni.so] Error 1
make[1]: Leaving directory `/payporte/android/application/android/app'
:app:ndkBuild FAILED

**Comment by K-Constantine** [comment]
i already used the one from git clone https://chromium.googlesource.com/external/gyp.git ./deps/gyp . it had the android.py in it's deps/gyp/pylib/gyp/generator folder. thanks for the everything buddy, appreciate it alot

**Comment by slynid** [comment]
Does above solution work on linux os
