### ISSUE TITLE
Compile java/jni on linux

### ISSUE THREAD

**Issue by pwais** [dropbox/djinni#136]
I'm trying to compile (at least for now) just the java/jni unit test and the current dependence on `std::experimental::optional` is a real stickler; the default clang 3.4 package for ubuntu isn't set up to include it.   have anybody ever tried compiling any of djinni on Linux?  are there any suggestions for working around / omitting `std::experimental::optional` ?  or to at least make it ... optional ;) ?  (It's still in review and is not technically required if a djinni IDL doesn't use it).

cc @mknejp

**Comment by j4cbo** [comment]
It's possible to use a standalone implementation of `optional` with Djinni with the `--cpp-optional-header` and `--cpp-optional-template` parameters. There's a good one at https://github.com/akrzemi1/Optional

**Comment by pwais** [comment]
Thanks @j4cbo !  I was able to get all the C++ code compiling fine using that lib.

It seems that OpenJDK 7's `javac` breaks on the non-escaped unicode characters in [ClientInterfaceImpl.java](https://github.com/dropbox/djinni/blob/master/test-suite/handwritten-src/java/com/dropbox/djinni/test/ClientInterfaceImpl.java#L6) unmappable...  would it be worth patching those to escaped unicodes?

I found some other nits with the Makefile that are not portable to Linux (e.g. `-dynamiclib`).  Would there be any interest in a patch that includes a Linux-capable build (for JNI only)?  If so, might using CMake be OK?

Finally, is `-std=c++1y` / C++14 required, or was #80 meant to remove that? (Did the authors decide to drop a requirement of C++14?  If so, is there any interest in making https://github.com/akrzemi1/Optional an official dependency vs having tests use `-std=c++1y` for XCode? AFAICT `std::optional` did not make it in to C++14 anyways ... )

**Comment by pwais** [comment]
derp, patch for the UTF-8 issue: https://gist.github.com/pwais/b595afcd4d896e113ae8

**Comment by pwais** [comment]
FWIW here is a patch with changes I made for Trusty: https://gist.github.com/pwais/e5a1ee3050604dc3f480 (plus using the Optional code that j4cbo recommended). 

It seems the default LLVM package in Utopic includes `<experimental/optional>` and so checking out Optional is not needed.  

One other thing I noticed: Java 8 is now a requirement due to the tests' use of `java.time`.

I'm planning to work on ironing this out into a more portable change.

**Comment by pwais** [comment]
I've started a branch to build and run the tests in linux (using CMake for portability): https://github.com/dropbox/djinni/compare/master...pwais:pwais_linux_build

Currently, `ant test` completes successfully on both OSX 10.9.4 as well as Debian Jessie.  I note that the Debian run produces some interesting JNI-related warnings: https://gist.github.com/pwais/418db1260939fd56f78e  <-- Lots of "JNI call made without checking exceptions" warnings.

To repro, run `test-suite/java/docker/linux_test.py` in that branch.  

@j4cbo, have you seen the warnings linked above before?  Perhaps OpenJDK has some JNI peculiarities that Android does not have.

I plan to add some testing for Ubuntu and clean up some other items before completing a PR.  The goal here is to make djinni easy to use for Java projects on (desktop / server) Linux.

**Comment by pwais** [comment]
FWIW, I'm hoping this gains inclusion into djinni such that djinni can be used in https://issues.apache.org/jira/browse/SPARK-10399

**Comment by j4cbo** [comment]
Fixed by #140, right?

**Comment by pwais** [comment]
Yea, I think I vote we can close this issue :)

It might be nice to support libc++ < 4.9 but seems to me that *nix packages are picking up quickly enough to ignore this issue.  The discussion here and the pointer to akrzemi1/Optional should help anybody who has similar problems.
