### ISSUE TITLE
Generated C++ and ObjC interface with --ident-cpp-type formatting set to non-default fails to compile

### ISSUE THREAD

**Issue by jrogers** [dropbox/djinni#137]
An easy way to reproduce is to take the token.djinni from the test-suite:
token = interface +c +j +o {
  whoami() : string;
}

Then modify test-suite/run_djinni.sh to have pass "--ident-cpp-type foo_bar". You will notice that the proxy class in the DBToken+Private.mm generated will be of ObjProxy type, but the toCpp/fromCpp functions will try to get it from the DbxObjcWrapperCache as a "objc_proxy".

My knowledge of scala is limited but it seems in ObjcppGenerator.scala, that it always generates the proxy class name as ObjcProxy, but when it generates the code the DbxObjcWrapperCache lookup, it uses objcppMarshal.helperClass("objc_proxy") which returns objc_proxy incorrectly.

Should that just be ObjcProxy instead of objc_proxy, since it's already being generated as ObjcProxy elsewhere?

**Comment by jrogers** [comment]
Note changing the objcppMarshal.helperClass("objc_proxy") calls to objcppMarshal.helperClass("ObjcProxy") does fix the problem for me...

**Comment by mknejp** [comment]
The name of that proxy should not depend on identifier styles because it's only ever seen by auto-generated code. So the proper approach is to hardcode `ObjcProxy`.
