### ISSUE TITLE
(objective-c)How to force declare a nonnull param or return value in .djinni file?

### ISSUE THREAD

**Issue by OpenFibers** [dropbox/djinni#138]
Is there a way to generate nonnull param or value, like `optional<typeA>` does for nullable values?
Only nullable declarations appears in my auto generated code, without the missing nonnull declarations, this produces many warnings in Xcode 6.4.

**Comment by j4cbo** [comment]
Currently interfaces are always nullable unless you're using the C++ nonnullable pointer support (the `--cpp-nn` parameters, see also https://github.com/dropbox/nn). We may support nonnull-by-default without enforcement, but that poses challenges for the test suite (I'm wary of introducing too many modes in which Djinni can generate code).

**Comment by OpenFibers** [comment]
@j4cbo nonnull or nullable, either is good for default value, since when a nonnull or nullable declaration occurs in a method header, other declaration without nonnull or nullable in this file's method header will becomes a warning in Xcode 6.4 or Xcode7.x. 
I modified scala generator to give method args default nonnulls, it seems to be a dirty way to archive this, or maybe I misunderstood the usage of djinni : (

**Comment by j4cbo** [comment]
Hm, we already do try to annotate everything one way or the other, e.g. https://github.com/dropbox/djinni/blob/master/test-suite/generated-src/objc/DBTestHelpers.h - so you may be running into a bug. Can you paste the .djinni file you're using and the ObjC output that has incomplete annotations?
