### ISSUE TITLE
What's different between djinni and ProtocolBuffer?

### ISSUE THREAD

**Issue by foobra** [dropbox/djinni#139]
Are these two have the same goal?

**Comment by j4cbo** [comment]
Very different.

Protobuf (and related projects like FlatBuffers, Cap'n Proto, etc) define serialization formats. They're a good choice when you need to store structured data on disk or send it over a network and access it from different programs written in different languages. They're commonly used for RPC systems (and some projects like Thrift define both serialization and RPC).

Djinni is designed for writing a single program, running in one process, in multiple languages. So it doesn't define a serialization format - everything is in-memory. It deals with objects as well as data, so you can have a `shared_ptr` that owns a Java object (or a Java object that owns a `shared_ptr` to a C++ object), and pass those references freely across the language boundary.

You could use both in the same project for different things. Djinni recently grew support for external types (thanks to @mknejp), so a protobuf-defined object could become a first class citizen in Djinni.
