### ISSUE TITLE
error: 'auto' return without trailing return type; deduced return types are a c++ 14 extension

### ISSUE THREAD

**Issue by levifan** [dropbox/djinni#144]
in XCode 7, when I try to build ios project, it shows the error below,
'auto' return without trailing return type; deduced return types are a c++ 14 extension

and then I can see the error point to the file  support_lib/source/proxy_cache_impl.hpp
line 40: template <typename T> static inline auto upgrade_weak(const T & ptr) { return ptr.lock(); }

anyone can give me any feedback? thanks!

**Comment by artwyman** [comment]
We use C++14 internally so this was probably just missed in testing.  I haven't looked deeply yet, but you can likely fix it if you add "-> decltype(ptr.lock())" after the function declaration.

**Comment by levifan** [comment]
Now when I tried to use iPhone simulator, then I got the many errors: Undefined symbols for architecture x86_64. And then I switched to iPhone Device, the errors would be: Undefined symbols for architecture arm64.

**Comment by artwyman** [comment]
What are the symbols which are missing?  That kind of error should be unrelated to Djinni, since it only generates source code, and doesn't specify architecture or build settings.  I suspect if you might've forgotten to include the Djinni-generated files in the target you're building.  Or otherwise you might have the wrong target architecture (ARCH), which may want to be something like $(ARCH_STANDARD_INCLUDING_64_BIT).

**Comment by levifan** [comment]
OK, I found the reason, I forgot to rename main.m to main.mm. Thanks you all!

**Comment by GustavoCostaW** [comment]
@levifan @artwyman I have the same problem, when I build to simulator or device, I receive Undefined symbols for architecture (arm real device or x86_64 emulator) error, can you help-me?

**Comment by artwyman** [comment]
@GustavoCostaW I don't think there's a general issue to resolve here.  Undefined symbols can come from lots of different causes.  @levifan's issue was specific to his code, and unrelated to the actual subject of this issue.  I might be able to suggest something to help with your specific issue with more detail.
