### ISSUE TITLE
License not filled out

### ISSUE THREAD

**Issue by r0mai** [dropbox/djinni#145]
I don't know how much it matters from a legal point of view, but your license is not actually filled out :)

https://github.com/dropbox/djinni/blob/master/LICENSE#L190

**Comment by artwyman** [comment]
I believe that text in the license file is just the how-to on how to apply the license.  The actual text is supposed to be filled in when the boilerplate appears in a source file like this: https://github.com/dropbox/djinni/blob/master/src/source/JNIGenerator.scala#L2

**Comment by r0mai** [comment]
Ohh, I see. Makes sense
