### ISSUE TITLE
link warning: object file (...) was built for newer iOS version (9.0) than being linked (6.0)

### ISSUE THREAD

**Issue by levifan** [dropbox/djinni#150]
In XCode 7.0, I got many link warning below,
ld: warning: object file (***) was built for newer iOS version (9.0) than being linked (6.0).
How can I fix these warnings? I have to set deployment target to iOS 6.0.

**Comment by j4cbo** [comment]
Hm, interesting. Are you including the support library as a subproject or as separate files? If it's a subproject, it may have a separate deployment target setting. This may also be a gyp issue, if that's how you're generating the project files.
