### ISSUE TITLE
WARNING in native method: JNI call made without checking exceptions when required

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#152]
I just upgraded to latest JDK 8 and am getting this warning for basically every C++ -> JNI call when running the test-suite:
```
     [java] .WARNING in native method: JNI call made without checking exceptions when required to from CallIntMethodV
     [java] 	at com.dropbox.djinni.test.TestHelpers.checkSetRecord(Native Method)
     [java] 	at com.dropbox.djinni.test.SetRecordTest.testJavaSetToCppSet(SetRecordTest.java:25)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:497)
     [java] 	at junit.framework.TestCase.runTest(TestCase.java:176)
     [java] 	at junit.framework.TestCase.runBare(TestCase.java:141)
     [java] 	at junit.framework.TestResult$1.protect(TestResult.java:122)
     [java] 	at junit.framework.TestResult.runProtected(TestResult.java:142)
     [java] 	at junit.framework.TestResult.run(TestResult.java:125)
     [java] 	at junit.framework.TestCase.run(TestCase.java:129)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:255)
     [java] 	at junit.framework.TestSuite.run(TestSuite.java:250)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:255)
     [java] 	at junit.framework.TestSuite.run(TestSuite.java:250)
     [java] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
     [java] 	at org.junit.runners.Suite.runChild(Suite.java:127)
     [java] 	at org.junit.runners.Suite.runChild(Suite.java:26)
     [java] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
     [java] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
     [java] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
     [java] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
     [java] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
     [java] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
     [java] 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
     [java] 	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
     [java] 	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)
     [java] 	at com.dropbox.djinni.test.AllTests.main(AllTests.java:29)
```

**Comment by artwyman** [comment]
I've been able to track down most but not all of these warnings.  I fixed many of them by sprinkling in more calls to jniExceptionCheck() in support library code.  However there are 3 warnings remaining, which I've pasted below.  I've looked for all instances of those JNI functions in our code and don't see any issues.  I also note that all the warnings I fixed listed the "V" (varags) variant of a function (like CallIntMethodV in the original issue).  This suggests that all our standard JNI calls eventually filter down to that form.  The 3 warnings which remain all have no such suffix, and 2 of them don't have a stack trace.  I theorize they're from a different kind of code, possibly junit or some other system thing (the one stack trace is in a call to Object.getClass during TestResult.endTest).

[java] WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
     [java] WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethod
     [java] Nov 10, 2015 8:19:39 PM com.dropbox.djinni.NativeLibLoader loadLibrary
     [java] INFO: Loaded /Users/atwyman/src/xplat/tools/code_gen/djinni/test-suite/java/build/local/lib/libDjinniTestNative.dylib
     [java] JUnit version 4.11
     [java] .........................WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
     [java] 	at java.lang.Object.getClass(Native Method)
     [java] 	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.getEffectiveClass(JUnit38ClassRunner.java:53)
     [java] 	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.asDescription(JUnit38ClassRunner.java:49)
     [java] 	at org.junit.internal.runners.JUnit38ClassRunner$OldTestClassAdaptingListener.endTest(JUnit38ClassRunner.java:31)
     [java] 	at junit.framework.TestResult.endTest(TestResult.java:82)
     [java] 	at junit.framework.TestResult.run(TestResult.java:127)
     [java] 	at junit.framework.TestCase.run(TestCase.java:129)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:255)
     [java] 	at junit.framework.TestSuite.run(TestSuite.java:250)
     [java] 	at junit.framework.TestSuite.runTest(TestSuite.java:255)
     [java] 	at junit.framework.TestSuite.run(TestSuite.java:250)
     [java] 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
     [java] 	at org.junit.runners.Suite.runChild(Suite.java:127)
     [java] 	at org.junit.runners.Suite.runChild(Suite.java:26)
     [java] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
     [java] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
     [java] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
     [java] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
     [java] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
     [java] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
     [java] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
     [java] 	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:96)
     [java] 	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:47)
     [java] 	at org.junit.runner.JUnitCore.main(JUnitCore.java:40)
     [java] 	at com.dropbox.djinni.test.AllTests.main(AllTests.java:29)
     [java] ...
     [java] Time: 0.026

**Comment by artwyman** [comment]
I think I've fixed as much of this as I can do.  Leaving the issue open for now, in case someone comes up with other ideas.

**Comment by j4cbo** [comment]
The first two are definitely not our problem. On my MBP with latest Java 8:
```
$ echo 'public class Foo { public static void main(String[] args) throws Exception { } }' > Foo.java
$ javac Foo.java
$ java -Xcheck:jni Foo
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethod
$ 
```

**Comment by j4cbo** [comment]
Add `System.runFinalization(); System.runFinalization();` (has to be twice) and you'll get the third one too. I think it's safe to close this.

**Comment by artwyman** [comment]
Sounds reasonable.  I'd kinda like some way to suppress these warnings without also suppressing any future instances of real warnings, but I don't know of one, so figure we'll just have to live with learning to ignore these 3 warnings for now.
