### ISSUE TITLE
Using djinni in Windows 7

### ISSUE THREAD

**Issue by emailsubbug** [dropbox/djinni#170]
Can anyone share the steps for using djinni in windows 7 ? i downloaded djinni-master fro git-hub. i am not clear on steps for using djinni for generating jni wrapper and cpp files. Please help the steps for one example solution. Thanks you, Subbu

**Comment by artwyman** [comment]
I don't know if there's any existing success with that.  I'd suggest joining the Slack community mentioned in the readme to get thoughts from more people.  What I know is that the code generated by Djinni will work on Windows (including with MSVC), but the only cases I know of it being used for that did the actual generation on Linux or Mac then checked the generated code into source control.

The limiting factor isn't Djinni itself, but the build scripts and test suite which depend on things like bash.  It probably would be quite possible to get them running on Windows using Cygwin or somesuch, subject to some tweaking and shaking out of bugs and assumptions.  Running on Windows without that would involve porting some scripts to Python or something.  Pull requests would be welcome if someone addresses this, but it's not on the Dropbox priority list at the moment.

**Comment by vmaks** [comment]
Hi,
Try to use MinGW or Git on windows instead of cygwin.
I have fixed an issue with windows build:
https://github.com/dropbox/djinni/pull/200

Steps are here:
http://mobilecpptutorials.com/
