### ISSUE TITLE
Objective-C object constants can crash on startup

### ISSUE THREAD

**Issue by artwyman** [dropbox/djinni#171]
This is an issue we've seen in the Dropbox apps causing occasional crashes.  C++ global static initializers run early enough that the Objective-C run-time isn't guaranteed to be ready, so creating most kinds of ObjC objects is unsafe.  Due to this, in pure ObjC (not ObjC++) initializers are only allowed to be compile-time constants of primitive type, or @"string" literals.  (Not even @1 or @[] or @{} are allowed.)  Djinni violates this with the initializers for constants of non-primitive types.

I'm posting this here to get feedback before implementing a fix, since the fix is likely to be compatibility-breaking.  I thin the right pattern is to switch from global constant variables to class methods.  So if you have a record my_record with a constant my_constant, today you use a variable like PFXMyRecordMyConstant, and instead you'd use a call like [PFXMyRecord myConstant].  +myConstant would be a class method which does lazy initialization using a function-scoped static.  I think that can be made to work even with extensible records, where the class method would be implemented on the PFXMyRecordBase class, but inherited by the user-supplied PFXMyRecord class.

I'm wondering what existing users think of the usability of that.  I'm also considering whether to duplicate the constants in both forms cases which are safe (primitives and strings), since the overhead of an ObjC method call seems like overkill when the constant is just an int.

**Comment by mknejp** [comment]
Well that's interesting.

I guess having class methods is the solution then. The nice thing is that a method `+foo` can be accessed like a property `MyClass.foo`. And if we override `+initialize` we don't have to worry about lazy initialization per variable which has its own problems.

I'm not sure about the duplication thing. It makes sense for primitives but it's also very good at confusing users why there are two options and when to use which. Change the type of a constant may result in changing code everywhere.

**Comment by j4cbo** [comment]
I think my vote would be to change the generated code for constants only where necessary (i.e. leave strings and non-optional numbers as-is). This means we'll generate different code for different types of constants, but:
- The only code broken by the change will be by necessity
- There's already precedent for similar stuff (this reminds me of the interface vs. protocol distinction)
- Use of extern constants of primitive type is definitely idiomatic in ObjC. (An example I remember seeing a while back: the ` NSURLSessionTaskPriority` constants in `NSURLSession.h`)
