### ISSUE TITLE
Compile error on optional Java interfaces

### ISSUE THREAD

**Issue by jefftrull** [dropbox/djinni#174]
I'm having trouble building an interface that takes as a parameter an optional interface:

```
if1 = interface +c {
    method(i : optional<if2>);
}

if2 = interface +j {
}
```

Compiling this results in a type conflict between the jni call (in NativeIf1.cpp) supplying an argument of type `djinni::Optional<std::experimental::optional, ns::NativeIf2>::CppType` and the cpp header definition (in if1.hpp) which gives the parameter type as `const std::shared_ptr<ns::If2>&`.  Am I missing an implicit conversion somewhere?  Thanks.

**Comment by artwyman** [comment]
Looks like a case we missed when adding nn<> support.  Fix coming soon, along with tests to validate.  @j4cbo I'd love to get your eyes on the fix, since you did the nn<> support.
