### ISSUE TITLE
Any plans for swift support?

### ISSUE THREAD

**Issue by rajeevnarayanan** [dropbox/djinni#181]
Swift has many advantages over IOS and it is gaining traction. Any plans to support swift?

**Comment by mknejp** [comment]
The only way to bridge C++ and Swift is to go via Objective-C. All you need to do is create a bridging header and you're ready to use the generated Objective-C classes in Swift. We could in theory generate the bridging header though.

**Comment by j4cbo** [comment]
Yep, we don't directly generate anything for Swift, but the ObjC code is intended to be "Swift-compatible", and we have made enhancements specifically intended to improve how the ObjC code looks in Swift: typed collections in #103 / #130, nullability annotations in 137c2ea8 (inspired by https://developer.apple.com/swift/blog/?id=25).

**Comment by hfossli** [comment]
Well, even though c++ can't interact with Swift directly, it is possible to bridge between Swift and Java/JNI. https://medium.com/@ephemer/using-jni-in-swift-to-put-an-app-into-the-android-play-store-732e542a99dd#.o37me05fo

**Comment by jonmcclung** [comment]
For people who arrive here via search engine, Djinni now generates the bridging header as of #342
