### ISSUE TITLE
Configurable include path for extended records

### ISSUE THREAD

**Issue by artwyman** [dropbox/djinni#184]
When Djinni generates an extensible record (record +c) it generates a MyRecordBase class, then assumes the developer will provide their own MyRecord class which inherits from it.  When it's necessary to include the header for MyRecord (e.g. in an interface which uses it), Djinni generates an include of "../my_record.hpp" (or similar for ObjC).

The "../" here assumes a certain directory layout used by Dropbox, where the generated always goes into a subdirectory "djinni_gen/" under the directory where the related hand-written code goes.  It would be better to make that configurable from the command-line so other code layouts can be supported via different relative paths, or just an empty string to include the header unqualified from some compiler include path.

**Comment by guycnicholas** [comment]
I was perusing the issues page and came across this one.  It was addressed in PR 203 and thus should probably be marked resolved shouldn't it?

**Comment by artwyman** [comment]
Yes it should, thanks.
