### ISSUE TITLE
std::optional instead of std::experimental::optional in generated files

### ISSUE THREAD

**Issue by ousenko** [dropbox/djinni#189]
djinni generates cpp files that use `std::optional` and `#include <optional>` from IDL like this
```i_bluetooth_api = interface +j {
    connect(address: string): optional<string>;
}```

In my Mac OS build setup (which follows [the proposed tutorial](http://mobilecpptutorials.com/your-first-cross-platform-djinni-app-part-1-cplusplus/)) this results in build error:

```
fatal error: optional: No such file or directory
 #include <optional>
```

I can fix it manually by replacing with proper `std::experimental::optional` namespace.
But what should I do to get djinni generate the proper code ?

**Comment by artwyman** [comment]
Since optional is non-standard, Djinni lets you specify your own version from the command-line.  You can see the relevant arguments in djinni/example/run_djinni.sh:

        --cpp-optional-template std::experimental::optional \
        --cpp-optional-header "<experimental/optional>" \

**Comment by ousenko** [comment]
That is just awesome, thank you very much!
