### ISSUE TITLE
Missing nn header include when implementing a method that has an argument of its own class

### ISSUE THREAD

**Issue by tiwoc** [dropbox/djinni#197]
Consider the following Djinni IDL:

	Foo = interface +c {
		useFoo(foo: Foo);
	}

	Bar = interface +c {
		useFoo(foo: Foo);
	}

When built with `--cpp-nn-header "<nn_header.hpp>" --cpp-nn-type "nn_type" --cpp-nn-check-expression "nn_check_expression"`, this generates the following headers (comments have been elided):

Foo.hpp
```cpp
#pragma once

#include <memory>

class Foo {
public:
    virtual ~Foo() {}

    virtual void useFoo(const nn_type<Foo> & foo) = 0;
};
```

Bar.hpp
```cpp
#pragma once

#include <memory>
#include <nn_header.hpp>

class Foo;

class Bar {
public:
    virtual ~Bar() {}

    virtual void useFoo(const nn_type<Foo> & foo) = 0;
};
```

Notice that Foo.hpp lacks the `#include <nn_header.hpp>` that is present in Bar.hpp.

**Comment by artwyman** [comment]
I can confirm that's a bug which I can reproduce.  @tiwoc want to take a stab at fixing it?  Should be something up with how the refs are handled in the CppGenerator.  Otherwise I can probably take a look at it sometime soon.

**Comment by tiwoc** [comment]
Thanks for the pointer, I'll take a look.
