### ISSUE TITLE
Generalize exception translation

### ISSUE THREAD

**Issue by j4cbo** [dropbox/djinni#2]
Right now, std::exception -> RuntimeException / NSException and that's it.

We want two things:
- Define other exception mappings (C++ my_exception -> Java MyException)
- Define exception types as records in the djinni file

**Comment by mrdomino** [comment]
+1

**Comment by artwyman** [comment]
There are now replaceable exception translation functions for both languages which allow customizing this (though they are still limited to exceptions in ObjC, not extra NSError** out parameters).  I talk about the Java side in our CppCon 2015 talk: bit.ly/djinnivideo2

**Comment by bvirlet** [comment]
How can I throw a custom exception from C++ to ObjC ? 

I can see how `throwNSExceptionFromCurrent` will throw a NSException, but I don't see how I can customize it to pass an custom error code back from C++ to ObjC.

Thanks.

**Comment by artwyman** [comment]
You can provide your own custom implementation of `throwNSExceptionFromCurrent()` in order to throw whatever you prefer.  The trick behind that is that Djinni's implementation of the function is marked as a "weak" symbol, so if you provide your implementation the linker should prefer your version without complaining about duplicate symbols.  I talked a little bit about the same trick on the Java side in our second CppCon talk: [bit.ly/djinnitalk2](bit.ly/djinnitalk2)

**Comment by bvirlet** [comment]
Thanks, this is helpful.

I'm adding the following to my project but it doesn't seem to override.
```
#include "DJIError.h"

#include <exception>

namespace djinni {
    [[noreturn]] void throwNSExceptionFromCurrent(const char * /*ctx*/) {
        try {
            throw;
        } catch (const std::exception & e) {
            NSString *message = [NSString stringWithCString:e.what() encoding:NSUTF8StringEncoding];
            [NSException raise:@"custom message" format:@"%@", message];
            __builtin_unreachable();
        }
    }
}
```
What's suspicious is that if I remove the `__attribute__((weak))` annotation from the Djinni provided method, I don't get any duplicate symbol errors.

**Comment by artwyman** [comment]
It would be hard for me to debug without more depth on your specific build system.  Sounds like this is iOS/Xcode, so it's not a different compiler than I'm using.  A common problem I might expect would be if the Djinni support-lib were fully-linked (e.g. into a dylib) before your re-definition is available, but it sounds like you're looking at both symbols in the same library.  You might try deleting Djinni's weak definition to see how that changes the behavior?  There might be some obscure compiler/linker flags you're using differently from us.

The general structure of what we do is build the Djinni support-lib and our overrides to it in two separate static library targets (in different Xcode projects generated by gyp, with identical build settings), then link them all together at the level of the final app executable.

**Comment by bvirlet** [comment]
Thanks, Andrew.

I've tried commenting out the Djinni weak definition, and my "strong" definition is then properly used.

Here is the command used to link the static library:
```
Libtool /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDK/libMySDK.a normal arm64
    cd /Users/bruno/Documents/_TheGrizzlyLabs/src/mysdk/prj-ios/MySDKDemo/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only arm64 -syslibroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -L/Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDK -filelist /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Intermediates/Pods.build/Debug-iphoneos/MySDK.build/Objects-normal/arm64/MySDK.LinkFileList -framework Accelerate -framework Foundation -o /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDK/libMySDK.a
```
I don't see any suspicious linker flags here.

Here is the command used to link the final app:
```
Ld /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDKDemo.app/MySDKDemo normal arm64
    cd /Users/bruno/Documents/_TheGrizzlyLabs/src/mysdk/prj-ios/MySDKDemo
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -L/Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos -L/Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDK -F/Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos -F/Users/bruno/Documents/_TheGrizzlyLabs/src/mysdk/prj-ios/MySDKDemo/Pods/../../../src/src_ios/Frameworks -filelist /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Intermediates/MySDKDemo.build/Debug-iphoneos/MySDKDemo.build/Objects-normal/arm64/MySDKDemo.LinkFileList -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Intermediates/MySDKDemo.build/Debug-iphoneos/MySDKDemo.build/Objects-normal/arm64/MySDKDemo_lto.o -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -ObjC -lMySDK -lc++ -lz -framework Accelerate -framework opencv2 -framework AssetsLibrary -lstdc++ -lPods-MySDKDemo -Xlinker -dependency_info -Xlinker /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Intermediates/MySDKDemo.build/Debug-iphoneos/MySDKDemo.build/Objects-normal/arm64/MySDKDemo_dependency_info.Ïdat -o /Users/bruno/Library/Developer/Xcode/DerivedData/MySDKDemo-fznbxrsrdneranebchjwqqmbcpor/Build/Products/Debug-iphoneos/MySDKDemo.app/MySDKDemoÏ
```
I have tried removing the -dead_strip option just in case but the weak version was still called.

For the sake of clarity, excluding the paths to libraries, the only linker options seem to be:
`-dead_strip -object_path_lto  -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -ObjC -lMySDK`

**Comment by artwyman** [comment]
I don't see anything obvious to explain the behavior you're seeing.  -ObjC might affect things if it were on the initial static lib (it's meant to keep all symbols) but it looks like it's only on the final app link?

If this is an issue which others might come across, and you can't find a workaround, we could consider a tweak in the Djinni repo to make this easier for you to do without modifying the sources.  We could add an #ifdef to allow compiler flags to remove the default weak implementation, or it could be moved into a separate source file so that you could decide to be selective about which files you compile (similar to the `djinni_main.cpp` file in the JNI support lib).
