### ISSUE TITLE
ProxyCache Problem

### ISSUE THREAD

**Issue by marzimdrums** [dropbox/djinni#204]
We were running into a problem, when we had a C++ class that has two delegates that have callbacks into iOS/Android code.

Our problem was then reducible to the proxy cache: If you now implement these two interfaces in the same Obj-C class with two protocols and then initialize the C++ class with one object implementing both protocols, then the proxycache will mix up the implementations that get called in Objective-C.

Just as an example how our code looked like, if the description is not clear:
`self.someObject = [SomeObjectWithTwoProtocols createWithDelegate1:self delegate2:self];`
where the callbacks are called on self from C++.

I haven't found any statement on this limitation. Of course, the advantages of the proxy cache clearly overweigh this particular use case that can trivially be done otherwise (just use one delegate instead of two).

**Comment by j4cbo** [comment]
Are you using the latest version of Djinni? This sounds like #179, which was fixed by 69402ad245f97ecbc297e2c035a3c0bf8be279a2.
