### ISSUE TITLE
Circular definition problem in objective c

### ISSUE THREAD

**Issue by canatella** [dropbox/djinni#21]
I'm trying to implement a delegate pattern:

device_discovery_delegate = interface +j +o {
    device_added(device: device);
    device_removed(device: device);
}

device = interface +c {
    static add_delegate(delegate: device_discovery_delegate);
}

When doing this, the generated  header Device.h imports DeviceDiscoveryDelegate.h which then references the protocol <Device> which is still not defined. I fixed this with this patch but I don't know if this is a good solution:

diff --git a/src/source/ObjcGenerator.scala b/src/source/ObjcGenerator.scala
index cd67a03..8d26b53 100644
--- a/src/source/ObjcGenerator.scala
+++ b/src/source/ObjcGenerator.scala
@@ -46,7 +46,7 @@ class ObjcGenerator(spec: Spec) extends Generator(spec) {
             header.add("#import " + q(headerName(d.name)))
           case DInterface =>
             header.add("#import <Foundation/Foundation.h>")
-            header.add("#import " + q(headerName(d.name)))
+            header.add("@protocol " + idObjc.ty(d.name) + ";")
             val ext = d.body.asInstanceOf[Interface].ext
             if (ext.cpp) body.add("#import " + q(privateHeaderName(d.name + "_cpp_proxy")))
             if (ext.objc) body.add("#import " + q(privateHeaderName(d.name + "_objc_proxy")))

**Comment by j4cbo** [comment]
Now fixed on master by @mknejp's refactor.
