### ISSUE TITLE
Crash when calling Java class method in native non-ui threads

### ISSUE THREAD

**Issue by ringyee** [dropbox/djinni#219]
Create a thread in native code, then in this thread, calling Java method will cause crash.

The root cause is in support-lib/jni/djinni_support.cpp/jniGetThreadEnv, when getting java thread env, since the native thread is not attached to java vm, the "env" returned in "g_cachedJVM->GetEnv" will be null.

Solution is calling AttachCurrentThread when env returns null:

```
JNIEnv * jniGetThreadEnv() {
    assert(g_cachedJVM);
    JNIEnv * env = nullptr;
    const jint get_res = g_cachedJVM->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (get_res != 0 || !env) {
        // :(
        std::abort();
    }

    return env;
}
```

==> 

```
JNIEnv * jniGetThreadEnv() {
    assert(g_cachedJVM);
    JNIEnv * env = nullptr;
    jint get_res = g_cachedJVM->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (get_res != 0 || !env) {
        get_res = g_cachedJVM->AttachCurrentThread(&env, NULL);
        if (get_res != 0 || !env) {
            // :(
            std::abort();
        }
    }

    return env;
}
```

**Comment by mknejp** [comment]
Please see #176 and #141 for why Djinni does not automatically attach to threads (the search function is your friend).

In short, it's impossible for Djinni to know when a thread exits to know when to detach a thread. Not detaching means leaking resources, not releasing locks, and not waking up waiting threads. Also known as deadlocks.

**Comment by ringyee** [comment]
@mknejp

Thanks for your reminding, I should search this issue before posting this thread

After reading 176&141, I've gotten the idea of not automatically attaching threads to vm. 

For my case, because I used a lib written before which used "pthread" to cross platform, and the created threads will exist always, so the best way for this situation is to attach automatically in Djinni support lib.
