### ISSUE TITLE
$ANDROID_BUILD_TOP not set; you need to run lunch

### ISSUE THREAD

**Issue by ganeshskudva** [dropbox/djinni#221]
Hello Folks,
I am just starting to use Dropbox jinni & was going through the tutorial to build android sample app available here:https://github.com/dropbox/djinni/tree/master/example

I hit this error, when I try to do:

```
cd djinni_root_dir
make example_android
```
I see this issue is exactly same as what I am seeing but reported almost a year ago:https://github.com/dropbox/djinni/issues/146

This above issue is closed with the solution being to use gcc4.9.
I checked my files & I see this 
**NDK_TOOLCHAIN_VERSION = 4.9** in 

> example/android/app/jni/Application.mk

Since **Issue 146** is closed,I am opening a new one. Any help will be highly appreciated.

**Comment by artwyman** [comment]
Can you share the specific error you're seeing?  If you're a new developer to Djinni and Android-NDK, the answer for you might be my initial answer in that old issue, from before the discussion moved on to other errors:

> The Makefile is looking for ndk-build in your path in order to fill in ANDROID_BUILD_TOP, by calling which ndk-build. You might need to add the appropriate directory to your PATH.

With the recent makefiles, you can also set the ANDROID_NDK_HOME environment variable to point to your NDK installation, instead of relying on path.

**Comment by ganeshskudva** [comment]
Hi Andrew,
                 Thanks for the response. I am a Android SDK developer new to Djinni. We are currently using SWIG to wrap our native C/C++ libraries into Java/ObjC. Djinni looks promising, hence we are planning to move over to it.

So coming to the issue at hand, I have **NDK_ROOT** & **ANDROID_NDK_HOME**(pointing to my NDK location. I am using NDK version 10) in my **.bash_profile**(I am running on Mac). This is the entire output when I run 

> make example_android
```
gkudva@gkudva-05211:~/Downloads/djinni-master$ make example_android
usage: dirname path
./example/run_djinni.sh
Already up to date: Djinni
Parsing...
Resolving...
Generating...
Copying generated code to final directories...
djinni completed.
ANDROID_BUILD_TOP= deps/gyp/gyp --depth=. -f android -DOS=android -Icommon.gypi example/libtextsort.gyp --root-target=libtextsort_jni
Traceback (most recent call last):
  File "deps/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "deps/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "deps/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "deps/gyp/pylib/gyp/__init__.py", line 511, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "deps/gyp/pylib/gyp/generator/android.py", line 970, in GenerateOutput
    assert android_top_dir, '$ANDROID_BUILD_TOP not set; you need to run lunch.'
AssertionError: $ANDROID_BUILD_TOP not set; you need to run lunch.
make: *** [GypAndroid.mk] Error 1
```

Thanks,
Ganesh

**Comment by gnichola** [comment]
Hi Ganesh, this doesn't answer your question, but there is a tutorial here: http://mobilecpptutorials.com/cross-platform-cplusplus-dev-setup-on-os-x-yosemite/ and if you look at that first page it goes through some setup steps.  It might be helpful if you check out the list of items needed and see which, if any, you are missing.

**Comment by artwyman** [comment]
Oops, looks like there's a bug in my Makefile code from Friday, so that ANDROID_NDK_HOME doesn't actually take effect.  If you add the NDK directory to your path, the existing makefile should pick it up (by running `which ndk-build` to find it).  Meanwhile I'll fix the Makefile's use of the environment variable and push that shortly.
