### ISSUE TITLE
modern packaging / release for djinni executable jar

### ISSUE THREAD

**Issue by pwais** [dropbox/djinni#222]
I've been using `run-assume-built` based upon the examples ( https://github.com/dropbox/djinni/blob/master/example/run_djinni.sh#L53 ) 

This can be a bit painful in a Docker context where I'd prefer to just run djinni using system-installed sbt and scala.  The `publish` target isn't super helpful right now... there's no main class defined in `build.sbt` for one thing.  I think `sbt` has come a long way since this project started.  What changes would we need to make a nice djinni executable?

**Comment by artwyman** [comment]
I haven't investigated this, and since I've only used Scala in the context of Djinni I'm not an expert in SBT.  I'd love it someone would find out and make this happen, though, to make the integration easier.
