### ISSUE TITLE
Platform-specific types

### ISSUE THREAD

**Issue by jawadst** [dropbox/djinni#229]
I am playing with OpenGL and cross-platform.

When writing C++ OpenGL code for Android, one needs to send the "Surface" to draw to from Java to C++ through JNI where the Android NDK can transform the Android "Surface" object into a window surface that OpenGL can draw to.

Example of Java code: https://github.com/tsaarni/android-native-egl-example/blob/master/src/main/java/tsaarni.nativeeglexample/NativeEglExample.java#L97
Example of JNI/C++ code: https://github.com/tsaarni/android-native-egl-example/blob/master/src/main/jni/jniapi.cpp#L61

This is not really replicable with Djinni at this point as there is no way to specify an Android-specific function that would take a Java type (Surface) in and translate it to a generic jobject. I understand that that kind of defeat the purpose of having a generic translation layer between multiple platforms but for games that mix C++ and native, there isn't much choice: at some point, the native part needs to send a surface to the C++ code.

Any opinion on how to best handle this case with Djinni?

**Comment by mknejp** [comment]
You can write external types that are translated in whatever way you want, and make it so that `Surface` is translated as `jobject` and `NSView*` remains `NSView*`. These are then consumed by Djinni the way you specifcy. See the section "Modularization and Library Support" on the main page.

**Comment by jawadst** [comment]
Thanks, it worked!
