### ISSUE TITLE
How to know some object returned from C++ is nullptr? In swift, it's "Some" and not nil

### ISSUE THREAD

**Issue by jacobjiangwei** [dropbox/djinni#232]
We are using swift to call objective c interface generated by djiini.

Some object returned in C++ are nullptr and it's correct.
But how can Swift know it's nullptr? It's actually "some" and raw point to some wrong address.

If I use "if object != nil" , it's always true.

How to resolve this issue?

**Comment by artwyman** [comment]
I don't know enough swift to help, but Djinni should generate objective C headers with the correct nullable or nonnull annotations, which should allow them to be bridged to Swift smoothly.  If you're getting the wrong behavior, it may be a result of the bridging header.
