### ISSUE TITLE
Async Android to C++ object lifecycle

### ISSUE THREAD

**Issue by pellet** [dropbox/djinni#233]
I currently have a static java object which I'm sharing with C++.
I'm ensuring it's increasing it's reference count in C++, however somehow the shared_ptr dangles after running a java async method from C++, even though the reference count was high and the java object was static.
Generally the code is working in my tests for example when ran on an emulator or when the test suite is ran by itself, however when I run all of my test suites on an Android device and the suite is one of the last ran, the dangling pointer occurs and I get a segmentation fault.
I was wondering if this could be to do with the way djinni works, I'm still new to JNI programming and I'm unaware of any consequences of using java objects in an async fashion on the c++ side.
Currently the only way I have been able to get around this segmentation fault is by passing the java object in again on the async method's completion handler and using this instance's reference instead of the old reference.

**Comment by artwyman** [comment]
I'm not sure I understand your use case well enough to advise.  There's nothing wrong with using objects asynchronously through Djinni.  If you keep the shared_ptr in C++ somewhere, it should hold a reference to a proxy object, which in turn holds a reference to the Java object.  If you can simplify your use case down to some sample code I can look at, I might be able to suggest more.

**Comment by pellet** [comment]
Thanks for trying.  Turned out to not have anything to do with djinni.  Just the fact that I thought the c++ lambda would be capturing my shared_ptr member instance.  However I had to assign it to a local variable for the lambda to capture it correctly.  If anyone has a similar problem, here is a post which solved my problem: http://stackoverflow.com/questions/19528375/lambda-capture-shared-ptr-member
