### ISSUE TITLE
narrowing implicit conversions in support lib cause warnings

### ISSUE THREAD

**Issue by jefftrull** [dropbox/djinni#234]
Building in Xcode for x86_64 revealed a couple of conversion warnings, which for us are promoted to errors: [here](https://github.com/dropbox/djinni/blob/master/support-lib/jni/djinni_support.cpp#L369) and [here](https://github.com/dropbox/djinni/blob/master/support-lib/jni/Marshal.hpp#L233).  On this architecture `size_type` is unsigned 64b and `jsize` is signed 32b.  A simple explicit conversion gets rid of the warning in both cases - see for example [my workaround](https://github.com/jefftrull/djinni/commit/3c6df174bb2f5ba228e69e6165b4036a6639aaa2).

**Comment by artwyman** [comment]
Can you go ahead and submit that as a PR?  Happy to merge it.  Thanks for pointing it out.

As an aside, I'm curious about what workflow causes you to be mixing building in Xcode with the JNI support library.  Communicating with Java running on a Mac?

**Comment by jefftrull** [comment]
Thanks!  I'll put one together.

This unusual configuration is a side effect of my goal to make all our unit tests, regardless of language, run on whatever platform we happen to be building on.  So now from the same IDE we can build iOS frameworks and run Java tests...
