### ISSUE TITLE
Error: "The system cannot find the path specified" on Windows

### ISSUE THREAD

**Issue by Avenza** [dropbox/djinni#236]
By default Djinni is using header default [std::optional](http://en.cppreference.com/w/cpp/utility/optional/optional), which is not yet available until C++17. 

I notice that I can use `boost::optional` by setting these: 

```
--cpp-optional-template "boost::optional" \
--cpp-optional-header "<boost/optional.hpp>" \
```

It works fine on Mac, but have an error on Windows: 

> The system cannot find the path specified

Anybody comes across the same problem?

**Comment by akire** [comment]
Yes, I'm having the same provblem. Seems to work fine when I remove the optional headers.
Any ideas how to solve this?

**Comment by artwyman** [comment]
I don't have any direct experience with boost, or with using Djinni on Windows, so I may not be able to be very helpful.  I know others have built on Windows who may chime in.  Or you could ask in the mobilecpp Slack community mentioned in the README.md file.

Many libraries did include optional before C++17 as std::experimental::optional, included as <experimental/optional.  It's also possible to use an independent implementation, which is what we do at Dropbox to avoid dependence on compiler differences.  We use the implementation from here: https://github.com/akrzemi1/Optional

**Comment by akire** [comment]
After some trying I fixed it by removing the "<" and ">" and using regular quotes instead. I don't know why that works, but it does. So the code would instead look like:

```
--cpp-optional-template "boost::optional" \
--cpp-optional-header '"boost/optional.hpp"' \
```

**Comment by xianwen** [comment]
<xxx> is for system headers, on linux, GCC would look for directories like "/usr/local/include" for them.
"xxx" is for user headers, for GCC, it would look for the paths specified via "-I" param.

I think you probably specified boost header in the user header search path, that's why you needed to use "".
If you're using Visual Studio, I think there should be 2 settings, one for user header search path, another for system header search path.

**Comment by artwyman** [comment]
Glad you figured it out.  I think that the distinction between angle-bracket includes and quoted-includes is implementation-dependend, so different compilers will handle it differently.  The best-practice I learned to follow was to reserve angle-brackets only for language+OS includes and use quotes for everything else.
