### ISSUE TITLE
Python test-suite fails using system Python on macOS 10.11+

### ISSUE THREAD

**Issue by artwyman** [dropbox/djinni#242]
There have been several reports of errors like this:

```
../handwritten-src/python/test_callbacks.py:7: in <module>
    from djinni.exception import DjinniException
../../support-lib/py/djinni/exception.py:1: in <module>
    from PyCFFIlib_cffi import ffi, lib
E   ImportError: dlopen(./PyCFFIlib_cffi.so, 2): Library not loaded: libmylib.dylib
E     Referenced from: /Users/danny/src/xplat/tools/code_gen/djinni/test-suite/pybuild/PyCFFIlib_cffi.so
E     Reason: unsafe use of relative rpath libmylib.dylib in ./PyCFFIlib_cffi.so with restricted binary
```

This seems to be a security restriction around library loading the system-installed version of Python starting with macOS 10.11 (El Capitain).  As a workaround, you can install a newer version of Python using `brew install python` which doesn't seem to be subject to the same security restriction.

It's unclear how to fix this in the test suite as-is, since the offending load happens inside the CFFI-generated .so, as it loads mylib.dylib.  An alternative might be for the test suite to statically link mylib and avoid the issue.

**Comment by xianwen** [comment]
Fixed in #331
