### ISSUE TITLE
Possible to make generated Java code package-private?

### ISSUE THREAD

**Issue by avf** [dropbox/djinni#245]
Hi,

I might be doing this wrong, but I'm writing an Android library which uses djinni and I'd like to keep the generated code out of my library's public API. As far as I can tell, the only way to do this would be to have the djinni `--java-package` be the same package as my library and then remove the `public` access modifier from the djinni generated sources. There doesn't seem to be a way yet to do this automatically.
I have a feeling I'm approaching this the wrong way. Is there a better way to achieve this?

**Comment by artwyman** [comment]
There's no existing feature for this.  The approach you suggest would work, and it wouldn't be too difficult to add a Djinni command-line argument to specify the visibility of generated Java classes (but it would take changes to the Djinni implementation, obviously).

Another approach I've taken to similar problems in the past (in pre-Djinni days) was to use class-file modifier to change visibility as a post-build step.
