### ISSUE TITLE
Android Parcelable

### ISSUE THREAD

**Issue by joshhaines** [dropbox/djinni#246]
Hello - we've started using Djinni recently on a few projects, and it is great. I'm not an expert at Android development, but our Android developer has pointed out that Android uses Parcelables to pass data between Activities using Intents. Has anyone else run in to this issue? If so, what approach did you take to get Parcelables from your Java generated classes? Or did you go with a different approach? On iOS we just pass the object in an init, but that doesn't seem to be the case on Android.

**Comment by artwyman** [comment]
We don't make use of Parcelable on Djinni records, though it's a feature we've discussed as a potential addition.  With some work, Djinni could auto-generate the necessary code for Parselable, similar to generating code for JSON serialization as proposed in #6.  I have no current plans to do it, but if you wanted to do do it I'd welcome the pull request.

**Comment by 4brunu** [comment]
@joshhaines You might want to take a look at https://github.com/dropbox/djinni/pull/308.

**Comment by 4brunu** [comment]
Since https://github.com/dropbox/djinni/pull/308 got merged, maybe this can be closed, because djinni already supports parcelable records
