### ISSUE TITLE
Rationale for @protocol in +c interfaces

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#25]
Hi,

I am currently in the process of trying out Djinni for our projects here. One thing that I am curious about is why the Objective-C side is using @protocol for the base type, but additionally also relies on a public @interface.

Specifically, if I have MyClass I get a @protocoll names MyClass and an @interface called MyClassCppProxy. Now as long as one only uses instance methods with id<MyClass> it's nice and all. But this totally makes object construction very inconvenient using class methods.

Example:
```
@protocl MyClass
+ (id<MyClass>) create;
@end
```

At first glance one might think you can call [MyClass create] but while this is great with static Java/C++ member functions that's not how Objective-C protocols work. One has to use [MyClassCppProxy create] instead. This is very inconvenient. First, I have to tell users about classes that I would consider a private implementation detail, and second, it means I have to tell our (overly religious) Objective-C developers to use something with "cpp" in its name...

Besides the inconvenience, there might also be a correctness issue. Right now all generated +c interfaces on the Objective-C side take id<Something> as parameter and then internally cast it to SomethingCppProxy* to get to the C++ object. But the argument may not necessarily be an instance of SomethingCppProxy. While this will most likely just crash the program I'd rather have it prevented at compile time if possible.

Both these issues would be solved if Djinni only created @interface types for +c interfaces. But I guess there is some rationale behind the current design and I would be curious to know about it.

Regards,
Miro

**Comment by mbrgm** [comment]
+1

**Comment by j4cbo** [comment]
Done!
