### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [dropbox/djinni#253]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _djinni_, deleted their software history.

https://github.com/dropbox/djinni/commit/b5bacd702e878c2a1cb0b474410190d82207c135

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask dijinni developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by artwyman** [comment]
Hi, Gustavo.  I'm happy to give some thoughts on this on behalf of developers at Dropbox.  I'm not sure if an issue is the right place for detailed discussion of this, though.  Feel free to reach out by email (my address is in the README.md file).  To be clear, history wasn't deleted, it was simply never published when an internal product became an open-source one.  In short, the history which is unpublished is history of Djinni's development internal to Dropbox, as well as the internal development of some new major features as they're added.  That history is available to us in an internal repo at Dropbox, but contains details of internal product development (such as unannounced product codenames, or links to our code-review server) which wasn't meant for public consumption.

If any non-Dropbox developers want to chime in about whether this practice has impacted their ability to contribute, feel free to comment.  I'm going to close out this issue, though.

**Comment by gustavopinto** [comment]
Hi @artwyman, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
