### ISSUE TITLE
Data type translations

### ISSUE THREAD

**Issue by fluxxion82** [dropbox/djinni#276]
So I hope this isn't a repeat question or anything; I looked around but didn't see anything. 
So there are a few data type translations I have some issues with, or more accurately, enhancement request for. Currently `list<type>`, `set<type>`,  and `map<typeA, typeB>` get translated to ArrayList, HashSet, and HashMap in Java, respectively. Why aren't those translated to List, Set, and Map java interfaces? Or is there anyway to add some options or flags so I can get those types of translations? Having to program to the actual implementation of these interfaces make things much less flexible. It seems like Objective-C doesn't really have this problem. NSArray doesn't look like it has an interface. But for Java this would make things so much more flexible and extensible, and all that jazz.
So is there a work around or way to get djinni to produce those java interfaces, or would it be a feasible and reasonable feature request?

Thanks so much for you time.

-Sterling

**Comment by artwyman** [comment]
I'm not sure what you mean about having to program the implementation of the interfaces. Do you mean that you have some other type of List and want to pass it as an argument to a Djinni interface without copying it into an ArrayList?  I can see that being a good idea, but it's not something currently supported.  I think the reasoning was that those specific concrete types are always what Djinni creates when it marshals data into Java, and it's useful to expose that to users who can take advantage of it (e.g. if you received a list from Djinni and wanted to do an efficient binary search on it).  In the other direction, I think that's not relevant, though the marshaling code does make assumptions about the specific container types for efficiency reasons.  For instance, the marshaling of lists makes a lot of calls to get(int) which would be inefficient on a LinkedList.  That could be changed to use an Iterator (which is already used for marshaling maps).

So, I think switching to generic interfaces would be a reasonable feature, though it would have some downsides for people currently making use of the specific types, so it might need to be a new configuration option.  An alternative you could try without new features would be to define whatever type of list you want to use as an external type using a YAML file.  You'd need to write some of your own marshaling code based on the existing examples, but then you could use whatever type you want.
