### ISSUE TITLE
Build warning about nullability type specifier for Xcode

### ISSUE THREAD

**Issue by kinglezhuang** [dropbox/djinni#277]
For Record type, Xcode build warning "Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)" for description func.

**Comment by guycnicholas** [comment]
An example of your idl file would be helpful here.  I know I have the warning level cranked up and I don't see the message you are mentioning.

**Comment by kinglezhuang** [comment]
item_list = record {
    items: list<string>;
}


#import <Foundation/Foundation.h>

@interface TXSItemList : NSObject
- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items;
+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * items;

@end


#import "TXSItemList.h"


@implementation TXSItemList

- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items
{
    if (self = [super init]) {
        _items = [items copy];
    }
    return self;
}

+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items
{
    return [[self alloc] initWithItems:items];
}

- (NSString *)description  ///  here
{
    return [NSString stringWithFormat:@"<%@ %p items:%@>", self.class, (void *)self, self.items];
}

@end

**Comment by guycnicholas** [comment]
You need a type for your list, what is it a list of? 

item= record {
   name: string;
   id: int;
}

item_lists = record {
   item: list<foo>;
   other_list: list<i32>;
   and_another: list<string>;
}

**Comment by guycnicholas** [comment]
@kinglezhuang does that make sense and solve your issue?
