### ISSUE TITLE
Fail to compile when non-nullable pointers options activated

### ISSUE THREAD

**Issue by bilsou** [dropbox/djinni#293]
I have been trying to use the `--cpp-nn-header`, `--cpp-nn-type` and `--cpp-nn-check-expression` options in order to let djinni use non nullable pointers by default. Nevertheless after pulling out the header from [https://github.com/dropbox/nn](url) and set it, I have no idea what to put for the 2 other options `--cpp-nn-type` and `--cpp-nn-check-expression`. 
Any idea ?

Thanks.

**Comment by artwyman** [comment]
We use a somewhat customized version within Dropbox, but I think if you're using the public version of nn.hpp you want something like this:

        --cpp-nn-header "\"<somepath>/nn.hpp\"" \
        --cpp-nn-type "dropbox::oxygen::nn_shared_ptr" \
        --cpp-nn-check-expression "NN_CHECK_ASSERT" \

You might also want to create your own macro which replaces NN_CHECK_ASSERT without the assert/if-check, since Djinni should guarantee that those are unnecessary.  We didn't include such a macro in the public version of nn<> because it's a scary thing which shouldn't be used most of the time.

**Comment by bilsou** [comment]
Thanks for the quick reply. 
I put that in my script, although the header seems to be found, I end up with this error. 

```
Compiling NYNetworkListener+Private.mm

❌  ios/objc_gen/NYNetworkListener+Private.mm:77:16: no template named 'nn'; did you mean 'dropbox::oxygen::nn'?

        return NN_CHECK_ASSERT(((NYNetworkListenerCppProxy*)objc)->_cppRefHandle.get());
               ^



❌  ios/objc_gen/NYNetworkListener+Private.mm:77:16: use of undeclared identifier 'i_promise_i_checked_for_null'; did you mean 'dropbox::oxygen::i_promise_i_checked_for_null'?

        return NN_CHECK_ASSERT(((NYNetworkListenerCppProxy*)objc)->_cppRefHandle.get());
      ^


** BUILD FAILED **
```

I might be doing something wrong.

**Comment by artwyman** [comment]
Oops, that seems to be a bug in nn.hpp, which wasn't noticed because the test file includes `using namespace dropbox::oxygen;`.  I just pushed a fix to the nn repo: https://github.com/dropbox/nn/commit/69dd88f12ffee42bc734b057348e3dacb588a4b9

**Comment by bilsou** [comment]
Just pulled out the latest nn version with your fix, compiles correctly now, thanks a lot.
