### ISSUE TITLE
Windows: path not found error

### ISSUE THREAD

**Issue by konovalov-aleks** [dropbox/djinni#298]
When you start a djinni, under windows, if one of the command-line arguments contains the symbol < and >, we get the following error: "the system cannot find the path specified":

D:\7\service-communicator\djinni>sh d:\7\djinni\djinni\src\run --cpp-optional-he
ader "<boost/optional.hpp>" --idl  person/person.djinni
Building Djinni...
[info] Loading project definition from D:\7\djinni\djinni\src\project
[info] Set current project to src (in build file:/D:/7/djinni/djinni/src/)
[success] Total time: 0 s, completed 08.02.2017 17:30:09
[info] Wrote start script for mainClass := Some(djinni.Main) to D:\7\djinni\djin
ni\src\target\start.bat
[success] Total time: 0 s, completed 08.02.2017 17:30:09
Системе не удается найти указанный путь.

**Comment by artwyman** [comment]
This seems likely to be a difference in how cmd vs. bash handle <> characters for redirecting and escaping.  Given that you're running sh manually here anyway, I think it might be preferable to put the arguments inside of a .sh script file, and run that script from the cmd prompt instead.  That way the arg passing is always from and to sh/bash.
