### ISSUE TITLE
Plan : use Djinni on windows

### ISSUE THREAD

**Issue by cdemez** [dropbox/djinni#307]
Hi,

I wish to know if there are plans to use Djinni on Windows with use Mingw (or similar) ? 

Other possibilities:
1) launch Djinni directly from a cmakelists.txt file ?
2) launch Djinni from a gradle script (mainly from Android Studio) ?

Is there any plan ?

Thanks

**Comment by artwyman** [comment]
Djinni doesn't officially support Windows (witness the extensive use of shell-scripts) but I think some folks in the community have experimented with it.  We at Dropbox don't have any plans to support it, but I'd be willing to merge PRs for Windows support if someone develops them.  For further discussion with the community, I'd suggest joining the Slack community mentioned at the bottom of the README.md file.
