### ISSUE TITLE
Auto-generate Java equals() methods for records

### ISSUE THREAD

**Issue by webmaster128** [dropbox/djinni#318]
At the moment, Djinni does not auto-generate Java's [equals](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object)) method for records. So records fall back on the identity equals implementation of Object when not overridden manually.

I think it would be a good default to say that two records are equals if and only if all their members are equal. Could this be auto generated from Djinni? Records with `+j` can still override the implementation from RecordnameBase.

**Comment by artwyman** [comment]
Djinni can already generate equality and ordering comparisons, but you need to request that on a per-record basis.  Check out "Deriving Methods" in the README.md file.

**Comment by webmaster128** [comment]
Thanks for the hint. Now I get the error from Djinni

> Cannot safely implement Eq on a record that may be extended

I guess this is because I use records with custom constructors. Can't we implement Eq in the auto-generated base class? This leaves room for customizations when a record is extended.

**Comment by artwyman** [comment]
That feature decision was from before my time as a Djinni maintainer, but I believe the logic was that if a record is extended, then the base class equality comparison can't be guaranteed to be accurate for any new members which are implemented in the subclass.  In C++ the comparisons are not virtual methods, so there could be potential incorrect results if a subclass object is compared via a reference/pointer to a base class.  Djinni is taking the guaranteed safe option here.  If you're extending the record, there's no reason you can't implement your own safe equality comparisons in the base class (albeit at the cost of some annoyingly manual effort).
