### ISSUE TITLE
The project is abandoned?

### ISSUE THREAD

**Issue by prsolucoes** [dropbox/djinni#320]
Hi,

What the status of this project? The project is abandoned?

I want add support to my other project (https://github.com/prsolucoes/native-kit), because with swig we cant generate objc/swift framework/binds.

Thanks.

**Comment by artwyman** [comment]
Not abandoned, no, though not super active.  Dropbox is still actively using Djinni for production code, but our use-cases haven't changed much in the past year or two, so we haven't been making major enhancements.  There are also other companies making active use of Djinni.

I'm the current Djinni maintainer, though my day-job is focused on other things.  I've been pretty lax for a while about reviewing and merging large changes/PRs (there are a few waiting on me, and several more waiting on authors).  I try to respond quickly to questions, and to small improvements or real bugs, though.

A good place to go for questions and discussion is the Slack community mentioned in the README, which includes folks from multiple companies using Djinni, and other technologies around C++ on mobile.  I'm going to close this issue and suggest you continue the conversation there if you wish.
