### ISSUE TITLE
DJIMarshal+Private.h: CFStringEncoding vs. NSStringEncoding

### ISSUE THREAD

**Issue by jgus** [dropbox/djinni#325]
I've hit a few compile errors in DJIMarshal+Private.h when trying to build Djinni-generated Obj-C interface code on Linux with GNUstep (yeah, yeah.) GNUStep provides `NSStringEncoding`, but _not_ `CFStringEncoding`, which is the return type of `getWCharEncoding` in DJIMarshal+Private.h, so the compiler takes issue with that.

However, looking at this code, I think it's slightly broken: `getWCharEncoding()` _declares_ a return value of `CFStringEncoding`, but the implementation _actually_ returns `NSStringEncoding` values. That return value is used in two places, both also in DJIMarshal+Private.h, on lines 157 and 165. The first calls `CFStringConvertEncodingToNSStringEncoding()` to "convert" the value (even though it's already actually an `NSStringEncoding`) and passes it to a message which expects an `NSStringEncoding`. The second (on line 165) just passes the return value directly to a message expecting an `NSStringEncoding`, casting it implicitly.

So, the use of `CFStringEncoding` here seems superfluous. It seems like `getWCharEncoding()` should simply return `NSStringEncoding`, and the call to `CFStringConvertEncodingToNSStringEncoding()` should be removed?

(Removing the references to `CFStringEncoding` also has the added bonus of unblocking building this code with GNUstep, as it happens...)

**Comment by artwyman** [comment]
That sounds plausible, and I agree from code inspection that it appears the enum types are being mixed (and not triggering any compiler warnings - sigh).  @konovalov-aleks is the author of the wchar feature, so I'd be interested in his opinion here.  @jgus go ahead and send a PR with a proposed fix and I'll give it a look.
