### ISSUE TITLE
Running into Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by tngan** [dropbox/djinni#338]
The build is failed when I tried to build the project.

I have already added the x86_64 architecture in build setting. Does anyone have similar issue before ?

```
Undefined symbols for architecture x86_64:
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::get(std::__1::type_index const&, std::__1::shared_ptr<void> const&, std::__1::pair<objc_object* __strong, void*> (*)(std::__1::shared_ptr<void> const&))", referenced from:
      OCDetector* djinni::get_cpp_proxy_impl<OCDetector, detector::Detector>(std::__1::shared_ptr<detector::Detector> const&) in OCDetector+Private.o
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::cleanup(std::__1::shared_ptr<djinni::ProxyCache<djinni::CppProxyCacheTraits>::Pimpl> const&, std::__1::type_index const&, void*)", referenced from:
      djinni::ProxyCache<djinni::CppProxyCacheTraits>::Handle<std::__1::shared_ptr<detector::Detector>, std::__1::shared_ptr<detector::Detector> >::~Handle() in OCDetector+Private.o
  "djinni::ProxyCache<djinni::CppProxyCacheTraits>::get_base()", referenced from:
      djinni::ProxyCache<djinni::CppProxyCacheTraits>::Handle<std::__1::shared_ptr<detector::Detector>, std::__1::shared_ptr<detector::Detector> >::Handle<>() in OCDetector+Private.o
  "djinni::throwNSExceptionFromCurrent(char const*)", referenced from:
      +[OCDetector create] in OCDetector+Private.o
      -[OCDetector hello] in OCDetector+Private.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by artwyman** [comment]
That looks like you probably didn't include the Djinni support library sources in your project.  You can find them here: https://github.com/dropbox/djinni/tree/master/support-lib/objc

**Comment by tngan** [comment]
@artwyman Thanks for your quick response. It works.

**Comment by ingviso** [comment]
@tngan I'm running into this same issue, how did you resolve this that is where did you add the objc files into your project?

**Comment by s-axford** [comment]
Hi, I am having a similar issue, but have added the support library sources to my Xcode project. My error reads:
"Undefined symbols for architecture x86_64:
  "demo::SharedCore::create()", referenced from:
      +[BDSharedCore create] in BDSharedCore+Private.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"
Is there another possible cause?

**Comment by artwyman** [comment]
demo::SharedCore::create() sounds like it's probably a static method in one of the interfaces you defined.  Have you defined such a function?
