### ISSUE TITLE
cannot find scala

### ISSUE THREAD

**Issue by ruffianhy** [dropbox/djinni#340]
when i run my script, it occured errors below:
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/Seq
	at djinni.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq

but my colleague works well with same script

I have install scala and it still cannot work.

**Comment by Dzamir** [comment]
I think I had the same problem when I installed JDK 8. Try to uninstall it and install JDK 7.

**Comment by artwyman** [comment]
Not really an issue, I'm closing this out.  I'd recommend joining the Slack group mentioned in the README to find more developers who might be able to help out.
FWIW I can build Djinni just fine with JDK 8.  Don't know what might be different for you.
