### ISSUE TITLE
C++ Exceptions

### ISSUE THREAD

**Issue by eto77** [dropbox/djinni#345]
Hi, when DJINNI_TRANSLATE_EXCEPTIONS is called ie from Objective C we are losing the original C++ stack trace in our error logs. Could you advise if there is any way around this?

Thanks.

**Comment by artwyman** [comment]
You can see an example of how to customize exception behavior here: https://github.com/dropbox/djinni/blob/master/extension-libs/jni-exceptions/custom_exception_type.cpp

The example is for JNI, but you can take a similar approach to ObjC by overriding `throwNSExceptionFromCurrent` defined here: https://github.com/dropbox/djinni/blob/master/support-lib/objc/DJIError.mm#L29

If you want custom behavior which can't be handled in this pluggable way, you could also modify the support-lib code by editing the `DJINNI_TRANSLATE_EXCEPTIONS` macro here: https://github.com/dropbox/djinni/blob/master/support-lib/objc/DJIError.h#L32

As for what to do in the customization, that depends a lot on the libraries you use, and the behavior you want.  C++ exceptions don't actually contain stack traces natively, so the only place you'll get one is in a crash when the exception is uncaught.  If you want C++ exceptions to be always be fatal, you could re-implement `throwNSExceptionFromCurrent` to just `throw;`, or replace `DJINNI_TRANSLATE_EXCEPTIONS` with something which doesn't catch anything.

If you want stack traces from non-fatal ObjC exceptions, it takes quite a bit of custom work, but I can describe what we do in the Dropbox codebase.  You first arrange to get stack traces into the C++ exception itself (using a stack-walker library of some sort in the exception constructor).  If you do that, it's possible copy that data in a custom NSException subclass, then override the `callstackSymbols` and `callstackReturn` methods on `NSException` to return something which includes C++ stack trace layers.

This is a question more than an issue in Djinin, so I'm closing out.  You might want to join the Slack community mentioned in the `README.md` file for further discussion.
