### ISSUE TITLE
Is optional<shared_ptr<T>> necessary?

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#36]
I get the intention behind specifying an `optional<T>` in the interface definition, stating that the passed in object reference may be `nil`/`null` in Obj-C or Java and this intention is clearly shown in the C++ side using `optional<shared_ptr<T>>` as argument or return type.

My problem with this is twofold:

1. `shared_ptr` already has a well defined *empty* state. Wrapping the whole thing inside `optional` seems redundant.
2. There is no indication in the Obj-C/Java interface telling a user where passing `nil` or `null` is OK or not, contrary to the C++ signature. The difference only manifests itself in the form of a runtime error if used incorrectly. Therefore whether a function accepts empty object references must be documented somewhere as one cannot infer it form the argument/return types.

My conclusion is getting rid of `optional<shared_ptr<T>>` and instead transform `nil`/`null` to/from *empty* `shared_ptr<T>` for interface types, regardless of whether they are defined as `T` or `optional<T>` in the Djinni file. However for plain `T` the generated code could handle `nil`/`null`/`nullptr` as errors and throw an appropriate exceptions to the offending code with an explanatory error message along the lines of "argument xxx may not be null", "return value must not be null" and so on.

Does that sound like a sensible thing to do?

**Comment by mrdomino** [comment]
I think it'd be totally reasonable to make optional<T> emit an un-std::optional<>'d shared_ptr in C++ code. I already read "shared_ptr" to mean "optional value that could be null." What if we only used optional<> for non-pointer types?

**Comment by mknejp** [comment]
New status on this is all interfaces are now nullable and transform `nil`/`null` <-> `nullptr`, so the C++ code has to assume the `shared_ptr` arguments may be empty. Djinni still accepts `optional<T>` where `T` is an interface, but there's no reason to use that anymore.

**Comment by j4cbo** [comment]
Totally agreed that we should never emit `optional<shared_ptr<T>>`. I'm starting to like the idea of having `optional` on interfaces correlate to annotations. Here's my understanding of the situation across languages - let me know if I'm missing something:
- Java has a few different annotations used for nullability checking, so we'd probably want to make the choice configurable (there's JSR 305, which is 'abandoned' but apparently still used, JSR 308, and Android has its own set).
- ObjC very recently got nullability specifiers (https://developer.apple.com/swift/blog/?id=25). We already emit these as of 137c2ea8fd12635ca29e98af6bffd3018e822451. They've come in handy for records, but at the moment interfaces are always tagged as nullable.
- C++ has `shared_ptr` and there is no standard idiom for a non-nullable `shared_ptr`. Internally we've actually built non-nullable `unique_ptr` and `shared_ptr` types, and we're planning to release them soon - so one option would be to add command-line options for "this is the type you should use for non-nullable pointers in C++".

**Comment by mknejp** [comment]
For C++ there are some proposals for defensive programming, that might be useful in the future.
Are there any static analyzers that use C++11 `[[attributes]]`?

Using it only for annotations is interesting. If the C++ classes were implemented as NVI `assert()` could be inserted by Djinni in the base implementation, but that would break existing code left and right.

**Comment by j4cbo** [comment]
Closing this since I think we're in a good shape with the new `nn` stuff, and haven't generated optional<shared_ptr> in a long time.

**Comment by jefftrull** [comment]
Can you guys update the docs on this?  They don't mention a difference in code generation between optional<POD> and optional<InterfaceType>... but I can see it's there in the results.  Little speed bump for me. Thanks!

**Comment by artwyman** [comment]
@jefftrull Pull requests welcome!
Less flippantly, yes, better docs would be great, for this, and lots of other things.  I may not get time to look at that before the holidays, though, and I want everyone in the community to feel empowered to make things incrementally better as they discover what's needed.
