### ISSUE TITLE
Android Debugging

### ISSUE THREAD

**Issue by EzimetYusup** [dropbox/djinni#375]
Hey guys, I am not being able to set a breakpoint to my C++ code in Android Studio 3.1.3, I remember i was able to do it before, anyone has any insights?
Note: I have put debuggable:true to build.gradle and have installed lldb
Thanks!

**Comment by artwyman** [comment]
Closing since this doesn't seem related to Djinni.  I'd suggest reporting to Android Studio, or a related forum?  If you're just looking to talk to people in the community to see if anyone else has the same issue, you can join the Slack community mentioned in Djinni's README.

**Comment by EzimetYusup** [comment]
it was Android sudio bug, i reinstalled and did work.
