### ISSUE TITLE
Better parcelable code generation

### ISSUE THREAD

**Issue by prsolucoes** [dropbox/djinni#393]
Hi,

I want suggest some enhancements to parcelable code generation, based on problems that i get today using the native library.

DATE FIELD (ex: expire date is a Date obj):

```
// write
dest.writeLong(this.mExpireDate != null ? this.mExpireDate.getTime() : -1);

// read
long tmpMExpireDate = in.readLong();
this.mExpireDate = tmpMExpireDate == -1 ? new Date() : new Date(tmpMExpireDate);
```

TYPED ARRAY LIST (ex: libraries is a list of product library):

```
this.mLibraries = in.createTypedArrayList(ProductLibrary.CREATOR);
```

**Comment by 4brunu** [comment]
Hey,

Regarding the DATE FIELD, I think your suggestion is good but has a problem, if the date is null, after being serialised the date will have the current date, so I suggest something like:
```
// write
dest.writeLong(this.mExpireDate != null ? this.mExpireDate.getTime() : -1);

// read
long tmpMExpireDate = in.readLong();
this.mExpireDate = tmpMExpireDate == -1 ? null : new Date(tmpMExpireDate);
```

Regarding the TYPED ARRAY LIST, I don't remember why it was made this way, I think it was to support all the types, including an array of dictionary. Did you had any problem with the current implementation?
```
// write
out.writeList(this.mList);

// Read
this.mList = new ArrayList<String>();
in.readList(this.mList, getClass().getClassLoader());
```

**Comment by prsolucoes** [comment]
Hi,

You are correct. So i suggest:

DATE FIELD:

```
new Date(0) // Thu Jan 01 00:00:00 UTC 1970
```

Djinni dont work with null objects.

TYPED ARRAY LIST:

Ok, correct. I test it here. List of hashmap need use writeList and readList.

**Comment by 4brunu** [comment]
Hey,

If you want to have a `Date` that can be `null`, you should make it `nullable` by declaring it `optional<date>` in the djinni file, that way, djinni works with null objects.

**Comment by prsolucoes** [comment]
Ok. I will close it for now.
