### ISSUE TITLE
Generated file with prefix on include headers

### ISSUE THREAD

**Issue by prsolucoes** [dropbox/djinni#394]
Hi,

Recently i pass by a problem on include paths. Two files with the same name. One i control because if from my project, but the other is from djinni. See an example:

https://github.com/ezored/dependency-string-helper/blob/master/build/djinni/jni-output/ezored/helpers/EZRStringHelper.hpp

And

https://github.com/ezored/dependency-string-helper/blob/master/build/djinni/jni-output/ezored/helpers/EZRStringHelper.cpp

And

https://github.com/ezored/dependency-string-helper/blob/master/build/djinni/objc-output/ezored/helpers/EZRStringHelper%2BPrivate.h

Every file has:

```
#include "StringHelper.hpp"
```

That is the header generated by djinni.

I want suggest an option in cpp or individual (cpp, jni, objc), that add a prefix to this include path. Example:

```
#include "${cpp_prefix}StringHelper.hpp"
```

It give us more control about include paths.

What team think about? Possible?

**Comment by artwyman** [comment]
I think you might be looking for the `cpp-include-prefix` cmd-line argument, which you can see here: https://github.com/dropbox/djinni/blob/master/src/source/Main.scala#L130

There are also other prefix args you can find in that same source file if I pointed to the wrong one.  You can also use the `ident-cpp-file` argument to change the C++ file names to not conflict.

**Comment by prsolucoes** [comment]
Arrrghhh. Djinni has everything!!!   :p

Thanks man.
