### ISSUE TITLE
Android Parcelable missing ArrayList import

### ISSUE THREAD

**Issue by skonstant** [dropbox/djinni#408]
I have a record that has sets no lists, and when the parcelable code is generated it creates something like:

 ArrayList<Long> mSubscriptionoasisTemp = new ArrayList<Long>();
 in.readList(mSubscriptionoasisTemp, getClass().getClassLoader());
 this.mSubscriptionoasis = new HashSet<Long>(mSubscriptionoasisTemp);

But since there is no list in the record, the import directive for ArrayList is not there, which breaks compilation.

The fix is not simple, I have a quick workaround for now but I don't think it will work with records that do have lists, it might import twice and break compilation again.

In JavaGenerator.scala:

override def generateRecord(origin: String, ident: Ident, doc: Doc, params: Seq[TypeParam], r: Record) {
    val refs = new JavaRefs()
    r.fields.foreach(f => refs.find(f.ty))

    if (spec.javaImplementAndroidOsParcelable && r.derivingTypes.contains(DerivingType.AndroidParcelable))
      refs.java += "java.util.ArrayList"

The last two lines fix it.

**Comment by artwyman** [comment]
@skonstant want to submit a PR for this fix?

I also wonder if the simple workaround you have above might be too broad for cases where a record implements Parcelable but doesn't contain any container types at all (sets, maps, lists) so won't need any readList() calls at all.

**Comment by 4brunu** [comment]
I just created a PR https://github.com/dropbox/djinni/pull/434 that fixes this issue.

**Comment by prsolucoes** [comment]
@artwyman can you merge it?
