### ISSUE TITLE
JNI headers include themselves

### ISSUE THREAD

**Issue by sasq64** [dropbox/djinni#422]
It seems JNI headers by default try to include the corresponding C++ header using just
`#include "InterfaceName.h"`, which just ends up including itself.
This can be worked-around by adding `--jni-include-cpp-prefix $(CPP_OUT_PATH)`.
So is it really the case that this flag is basically mandatory, or am I missing something?

**Comment by artwyman** [comment]
It is (somewhat confusingly) up to the user to resolve that name collision.  What you suggest is one way of doing it.  Another (which matches our use case at Dropbox) is to rename the JNI files with a prefix using `--ident-jni-file`.  #411 adds that to the example in `README.md`
