### ISSUE TITLE
Circular Dependencies for Record?

### ISSUE THREAD

**Issue by codingrhythm** [dropbox/djinni#440]
I have something similar to this

```
record_a = record {
  value: list<record_b>;
}

record_b = record {
  value: record_a;
}
```

and the generated code failed to build for cpp and Objective-C because of the circular dependencies. Any ideas? for `interface`, Djinni uses forward declarations to break circular dependencies. Can we support this for record as well? Thanks

**Comment by artwyman** [comment]
No, records contain their fields "by value", meaning that a circularly-defined type would be of infinite size.  If you need recursive types you need to implement them using custom interfaces, or come up with some other data format to pass them across the language boundary.
