### ISSUE TITLE
Discussion about merging works from LedgerHQ/djinni into this repository

### ISSUE THREAD

**Issue by phaazon** [dropbox/djinni#443]
Hello maintainers,

I would like to start a discussion about merging the work [we’ve been doing for quite a while at Ledger](https://github.com/LedgerHQ/djinni) into the original project. The idea is that we support other languages:

  - Scala.
  - Node.js / JS.
  - React-Native.

We’re also adding few features around, like a `void` type, generic callbacks (see [this](https://github.com/LedgerHQ/djinni/pull/22)), etc. Maybe you will think all of this is too convoluted to be merged into the upstream project and I would get it 100% cristal clear.

However, I think it’s interesting to start discussing between it would benefit everyone to have a single repository. 🙂 

What do you think? Cheers! 🍻

**Comment by artwyman** [comment]
It's awesome that you've been putting so much effort into enhancing Djinni!  At this point we're not going to be merging any major features into this repo, which is going into minimal/volunteer maintenance mode on the Dropbox side.  See the note the README which was added just last week. 
 I'd encourage you to join the Slack community mentioned in the README (if you're not already there) for discussion of Djinni's support status and alternative forks which might be available for new features.
