### ISSUE TITLE
Problems when compile djinni

### ISSUE THREAD

**Issue by prsolucoes** [dropbox/djinni#445]
Hi,

I have updated djinni from master (git pull origin master) and call make to build djinni again (make).

But get this error:
![image](https://user-images.githubusercontent.com/395096/57488978-1469a800-728b-11e9-8b71-7e0f42f3edfe.png)

Thanks.

**Comment by artwyman** [comment]
What does `python --version` print for you?  My hunch from that error message is that you might be running Python 3, while Gyp expects to run in Python 2.

**Comment by prsolucoes** [comment]
No more. Thanks. I will close.
