### ISSUE TITLE
Java to C++ exception translation

### ISSUE THREAD

**Issue by lottototto** [dropbox/djinni#49]
Common workflow with djinni (I'm focused on Java only now): "Client code" (Java) --> C++ library shared code --> Platform specific interface if necessary (again Java, TextboxListenerImpl in the example).

If we call platform specific code from C++ and it throws an exception, then it is caught by jniExceptionCheck and passed back to C++ as jni_exception_pending(), but no matter what C++ code does (catches it or not), exception still exists in JVM and client code is forced to catch it (even if C++ code has already recovered).
Any reason for this? Can JNI remove exception from JVM with env->ExceptionClear() before throwing jni_exception_pending()? Then we will have to catch exception only once (in C++ code). "C++ code" does call platform specific code and it should know better how to recover in case of exception. If it is necessary we still can re-throw it to client code, but in some cases client code should not care about this.

Any thoughts?
Thank you.

**Comment by j4cbo** [comment]
This has been fixed by d155107a92c8842cf41a6bb6aed97e6c96e85a23
