### ISSUE TITLE
Deriving objc header location when extending records

### ISSUE THREAD

**Issue by mbrgm** [dropbox/djinni#51]
When a record is specified to be extended in ObjC (using the `+o` flag), the deriving header location is always `../DerivingHeaderName.h` (see [here](https://github.com/dropbox/djinni/blob/0a146261b374735c44e2a5b1c1b8a8237414913e/src/source/ObjcGenerator.scala#L398)). Now that header is obviously a piece of handwritten code. I could not make this work while keeping the generated and handwritten source files in separate directories.

Wouldn't it be better to add an option for specifying were handwritten source files are located? Or is there some other way around this?

**Comment by artwyman** [comment]
Available now.  See the --<lang>-extended-record-include-prefix options
