### ISSUE TITLE
Cygwin uses incorrect paths

### ISSUE THREAD

**Issue by wbmoeller** [dropbox/djinni#58]
## sbt fails to find sbt_launch.jar when djinni is run from cygwin

The failure in cygwin is due to incorrect paths.  Java on windows requires windows-formatted paths, even when run from cygwin.

cygpath can be used to convert between the various formats.

**Comment by Frekimoto** [comment]
Hi!

I'm new at cygwin. Where did you put cygpath?

**Comment by vmaks** [comment]
Hi,
Try to use MinGW or Git on windows instead of cygwin.
I have fixed an issue with windows build:
https://github.com/dropbox/djinni/pull/200
