### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by wbmoeller** [dropbox/djinni#59]
Running djinni on windows fails due to generating target/start.bat but trying to exec target/start from run_assemble_built

For running on cygwin, it should generate a normal "start" and exec it.  Or, if it's running from a windows command prompt it should "start /WAIT start.bat".  The cygwin approach seems less problematic...

**Comment by vmaks** [comment]
Hi,
Try to use MinGW or Git on windows instead of cygwin.
I have fixed an issue with windows build:
https://github.com/dropbox/djinni/pull/200
