### ISSUE TITLE
Failing to build sample example on Ubuntu and Windows (using Cygwin)

### ISSUE THREAD

**Issue by prashant8579** [dropbox/djinni#66]
Failing with following error when trying to build using: make example_android

FAILURE: Build failed with an exception.

* Where:
Build file '/home/prashant/Work/Djinni/example/android/app/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':app'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
  	[class java.lang.String, class java.lang.String]
  	[class java.io.File, class java.lang.String]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Please suggest

**Comment by skabbes** [comment]
Make sure you have a local.properties file for your android project.  This is necessary to configure the android sdk and ndk location.  For a (perhaps) better supported example project check out [mx3](https://github.com/libmx3/mx3)

**Comment by prashant8579** [comment]
Thanks
