### ISSUE TITLE
A Barrel of Refactoring

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#70]
Hey folks,

over the past month or two Djinni was used quite extensively here and we ran into a few problems, resulting in a number of refactorings, both internal (not changing the output) and external (significantly changing the output). Besides, we need something similar to #52, which at the time posed quite a challenge considering how Djinni was structured. So in preparation to make #52 (and others like #54, #46, #45) much easier to realize something had to happen. 

Before doing a pull request I thought it'd be better to share these changes and get your input. So here we go:

* Split the `ObjcGenerator` into `ObjcGenerator` and `ObjcppGenerator`. This makes it easier to adjust only one of them and is also how the Java/JNI generators are separated. The philosophy here is that using only `ObjcGenerator`is sufficient to create all the Obj-C files necessary in the same fashion as `JavaGenerator` only creates Java classes, but no JNI content.
* Introduce "Marshal" types, responsible for naming types, files, creating parameter signatures, to/from C++ conversion, etc. Now every language has its own Marshal. The `xxxGenerators` are responsible for the overall file structure, whereas `xxxMarshals` do the actual language interop. So now `JNIGenerator` can make use of `CppMarshal` to create consistent type signatures etc. (This is a crucial part to make #52 remotely possible)
* The Obj-C support library was restructured similar to how the JNI support library works, using template translation types. This *wastly* simplifies the work of ObjcppGenerator.
* Before, Djinni was generating `@protocol` types for both `+c` and `+o` and provided a `xxCppProxy` in a `+Private.h` include file. This was a real thorn to every Obj-C developer exposed to Djinni generated types as it didn't really follow any existing conventions on that platform. Therefore came an implementation of #25. To recap: `+c` types now generate an `@interface` acting as proxy to C++ and `+o` types generate a `@protocol` to be implemented in Objc-C. Therefore `+c` types are represented by `T*` variables and `+o` by `id<T>`. There was similar outcry in the Java camp about `+j` not creating a Java `interface` instead of `class` but changing the JNI side is a bit more involved.
* Since Obj-C and Obj-C++ are now considered two separate generators, there's a new set of `--objcpp-x` command line arguments:
  * `--objcpp-out`: The output folder for private Objective-C++ files (Generator disabled if unspecified).
  * `--objcpp-include-prefix`: The prefix for `#import` of Objective-C++ header files from Objective-C++ files.
  * `--objcpp-include-cpp-prefix`: The prefix for `#include` of the main C++ header files from Objective-C++ files.
  * `--objcpp-include-objc-prefix`: The prefix for `#import` of the Objective-C header files from Objective-C++ files (default: the same as `--objcpp-include-prefix`)
  * `--objc-ext` => `--objcpp-ext`: The filename extension for Objective-C++ files (default: `"mm"`)
* Many inconsistencies about formatting and signatures are gone as that is all handled by single entities (aka Marshals).
* Since `ObjcGenerator` is setup to create self-containing Obj-C records it creates its own `.m` files containing the comparison functions, initializers, etc. separate from Obj-C++ translators. But because Obj-C only allows compile-time constants at file scope the file must have extension `.mm` to support constants of record types. Same applies to interfaces.
* The comparison operators for C++ records are generated as free friend functions to make them symmetric and follow best practices.
* JNI `fromCpp()` functions now all return `LocalRef<jobject>` instead of `jobject` and local reference cleanup is handled by it form there on.
* Generated code didn't always fully qualify the `::djinni` namespace for support library stuff

There may be other small fixes but those are the really important ones. It also includes fixes for issues #69, #26, #21, #10 and implicitly includes pull requests #67, #55, #42, #41, #39, #38 .

Do these changes break existing code? Hell yes, they do.
But at least the example and test-suite all pass.
I get that this kind of bulk change is a Bad Thing™, but never was there ever a point in the past 2 months where I could have said "yes, this is a small self-contained change that can be merged back now". There was (and still is) quite the amount of redundancy and intertwining. Also the reason why I'm doing this post first.

Anyway, the branch is here https://github.com/mknejp/djinni/tree/feature/codegen-refactor so check it out if interested and see how much code it breaks. You will definitely have to add the `--objcpp-out` option otherwise that part is going to be missing entirely. If it's fine I'll do the pull request and hop on to #52.

**Comment by j4cbo** [comment]
Awesome.

I just this week got back from an extended break, and I'm working on digging through the backlog (both internal and external-facing stuff). At first glance this looks great, e.g. #52 is something that's been on our wishlist for while. It'll be a few days before I have time to give this the attention it deserves, and in the meantime I'll be merging in a number of the smaller pull requests that have been sitting around.

Thanks!

**Comment by j4cbo** [comment]
Also, so this isn't a blocker later, can you fill in the CLA at https://opensource.dropbox.com/cla/ ? Thanks!

**Comment by mknejp** [comment]
done

**Comment by mknejp** [comment]
One grudge I still have is the deep copying behavior as generated in Objective-C. I feel like this is a remnant from when containers were still mutable. Now it seems there is no real reason to have deep copy operations when everything is immutable:
* All records have read-only properties
* Containers are either NSArray, NSSet or NSDictionary, all immutable
* NSData is immutable
* NSString, NSNumber, are immutable
* Interfaces are not copied at all

There's also the weird asymmetry that the Java code does not implement any deep copy operations. Is that an oversight or not necessary in Java?

I am inclined to ditch the deep copy stuff for this, it no longer seems to have a purpose.

Thoughts?

**Comment by j4cbo** [comment]
Hm, I agree that the deep-copy code seems unnecessary. We do have some call sites to it internally - I'm investigating to see what's going on there.

**Comment by alanjrogers** [comment]
> One grudge I still have is the deep copying behavior as generated in Objective-C. I feel like this is a remnant from when containers were still mutable. Now it seems there is no real reason to have deep copy operations when everything is immutable:

Definitely agree with this, I'd :heart: to see us remove the deep-copying if we can.

**Comment by j4cbo** [comment]
Agreed. I looked through the places we use that code internally and it'll all be going away soon, so ditching the deep copy init functions seems like the way to go.

We had a few changes in the pipeline here but I just finished sending them all up to github. Could you merge/rebase on top of the new master and start sending pull requests?

**Comment by mknejp** [comment]
Pull request is up here #74. It does not include #52.

Unfortunately it's quite the monster, but as already said it was very difficult to refactor in small packages. All the tests and the example were kept up to date and they all pass. I should probably do an update to the readme as well once this is through.
