### ISSUE TITLE
Something broke - tons redefinitions errors in generated code

### ISSUE THREAD

**Issue by yevgenyk** [dropbox/djinni#82]
I have started getting a whole bunch of redefinition errors after the latest refactoring commits.
 error: redefinition of 'Network'
 error: use of undeclared identifier 'ObjcProxy'

Source code is in: https://github.com/yevgenyk/Play2
and djinni definitions are here: https://github.com/yevgenyk/Play2/tree/master/djinni

the local make target is:
make tests 
or
make mac

and the failures in Xcode in Obj-C in ./mac_xcode/Play2.xcodeproj target called play_objc

**Comment by mknejp** [comment]
I cannot build your project, but I do see a problem with your namespaces. You generate all classes into `Play2_gen`, which creates conflicts because for each interface/record/enum defined in a djinni file a class with the same name is created for C++, Objective-C and JNI in their respective namespaces.

I suggest you change this to avoid collisions, for example:
```
  --cpp-namespace Play2_gen
  --objcpp-namespace Play2_gen::objcpp
  --jni-namespace Play2_gen::jni # This one is currently missing, not good
```
Maybe Djinni should enforce the use of namespaces and demand them to not conflict with each other.

**Comment by yevgenyk** [comment]
Thanks for pointing me to this configs, but there is still a problem.

The nested namespaces didn’t work for me so I opted for these:

    --cpp-namespace Play2_gen \
    --objcpp-namespace Play2_gen_objcpp \
    --jni-namespace Play2_gen_jni \

But it appears there is a confusion for this djinni definition:

@import "item.djinni"
@import "parsed_items.djinni"
@import "http_response.djinni"

network_params = enum {	
    URL;
    APIKEY;
    N;
    MAX;
}

network = interface +o +j {
    download(params: map<network_params, string>): http_response;
}

where http_response.djinni is like this:
http_response = record {
    	http_code: i16;
    	error: string;
	data: string;
}







Thanks!!!
Yevgeny

**Comment by mknejp** [comment]
> But it appears there is a confusion for this djinni definition:

Can you elaborate, what confusion?

As a side note: I suggest to format the enum fields like all other identifiers in the `foo_bar` way and then specify how to print them with the `--ident-xxx` options (check `--help` for details).

**Comment by yevgenyk** [comment]
The
virtual HttpResponse download (const std::unordered_map<::Play2_gen::network_params, std::string> & params) override;

call uses HttpResponse as is, without specifying its namespace,which is Play2_gen
the signature that compiles looks like this:

virtual Play2_gen::HttpResponse download (const std::unordered_map<::Play2_gen::network_params, std::string> & params) override;


Djinni picked up 

        static std::shared_ptr<::Play2_gen::Network> network_with_objc (id objcRef);

but failed on 

	HttpResponse download

likely because http_respons is a = record
or because it’s meant to be everywhere while 
network = interface +o +j




network = interface +o +j {
    download(params: map<network_params, string>): http_response;
}


http_response = record {
    http_code: i16;
    error: string;
	data: string;
}

**Comment by mknejp** [comment]
I just checked out your project with the current Djinni master and it builds fine.
There isn't really any confusion as the C++ `Network` class is defined inside the `Play2_gen` namespace, so the return type doesn't need to be qualified.

**Comment by yevgenyk** [comment]
ok, thanks, using separate namespaces and the latest djinni code helped. Please close this issue.
Yes, the `*-namespace` should be different and djinni should force them to be set. Either by user in case of this flag completely missing, or automatically, perhaps but appending something to each namespace. Or at least print a warning that there may be clashes.

Hunting down the namespace incompatibilities is very time consuming and people will likely to just abandon the project at this point. It's very important that the generated classes compile without any efforts, even if this means that some of the namespaces look long or weird.
