### ISSUE TITLE
Ditching Objective-C deep copying?

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#93]
This is a followup from a point raised in #70 that basically questioned the usefulness of the Objective-C deep copy code generation. To repeat the points brought up there:

- All records have read-only properties
- Containers are either NSArray, NSSet or NSDictionary, all immutable
- NSData is immutable
- NSString, NSNumber, NSDate are immutable
- Interfaces are not copied at all
- It's slow as hell and users run risk of deep copying stuff around by accidentally using the "wrong" initializer

There is no deep copying generated for Java and the value semantics of C++ make it available for free. It needlessly complicates ObjcGenerator, adding a new special case every time a new type is introduced.

Does anyone depend on this behavior being present?

**Comment by j4cbo** [comment]
We do, but for bad reasons. Specifically, there's a place where we have an ObjC-extended record, and the extended record is mutable - so it has a copy constructor, which invokes the Djinni-generated deep copy constructor.

I'm going to change that code to do a handwritten shallow copy instead. Extending a record and making it mutable feels like a code smell in the first place, so I don't think it's something Djinni needs to provide support for (especially given that it's easy enough to hand-write the copying code if needed anyway). I'll push a change that removes deep copy generation once the internal fix goes through.

**Comment by mknejp** [comment]
Wouldn't it suffice to make records implement `NSCopying` and simply provide a simple shallow copy?

**Comment by j4cbo** [comment]
That seems good for supporting the mutable-extension use case, but I don't think it's high priority (at least for us). I'll close this for now but feel fee to open up a new issue for the `NSCopying` TODO.
